### ISSUE TITLE
RegexpError: empty range in char class

### ISSUE THREAD

**Issue by gazay** [rubinius/rubinius#1503]
``` bash
0:code$ ruby -v
rubinius 2.0.0dev (1.9.3 4f01c07f yyyy-mm-dd JI) [x86_64-apple-darwin10.8.0]
0:code$ irb
rubinius-2.0.0dev :001 > c = '\u{80}-\u{D7FF}\u{E000}-\u{FFFD}\u{10000}-\u{10FFFF}'
 => "\\u{80}-\\u{D7FF}\\u{E000}-\\u{FFFD}\\u{10000}-\\u{10FFFF}" 
rubinius-2.0.0dev :002 > /[#{c}]/
RegexpError: empty range in char class: [\u{80}-\u{D7FF}\u{E000}-\u{FFFD}\u{10000}-\u{10FFFF}]
    from kernel/common/regexp.rb:97:in `initialize'
    from kernel/alpha.rb:96:in `new'
    from (irb):2
    from kernel/common/block_environment.rb:74:in `call_on_instance'
    from kernel/common/eval.rb:71:in `eval'
    from kernel/common/kernel19.rb:17:in `loop'
    from kernel/common/throw_catch19.rb:8:in `catch'
    from kernel/common/throw_catch.rb:10:in `register'
    from kernel/common/throw_catch19.rb:7:in `catch'
    from kernel/common/throw_catch19.rb:8:in `catch'
    from kernel/common/throw_catch.rb:10:in `register'
    from kernel/common/throw_catch19.rb:7:in `catch'
    from kernel/delta/codeloader.rb:67:in `load_script'
    from kernel/delta/codeloader.rb:109:in `load_script'
    from kernel/loader.rb:630:in `script'
    from kernel/loader.rb:834:in `main'
rubinius-2.0.0dev :003 > 
```

This error I got when tried to run new rails 3.2.0.rc2 app. Same regexp in sass gem.

**Comment by walterheck** [comment]
Which commit fixed this?

**Comment by brixen** [comment]
@walterheck I'm not sure which specific commit, this was a long time ago. There are a number of commits around the 1.9 Ruby parser, Regexp, and the oniguruma library around the date of this ticket.

Are you having an issue?
