### ISSUE TITLE
undefined conversion for unicode characters from UTF-8 to ASCII-8BIT

### ISSUE THREAD

**Issue by scottshea** [rubinius/rubinius#2163]
I am sorry if this is an ignorance thing. I did not see this under Ruby 1.9.3 but do now after switching to Rubinius. I go to parse JSON and get:

`undefined conversion for '"<p>On a very cold morning, it was -8°F. As the day went on, the temperature rose 2 degrees each hour. Which equation shows the temperature over time?</p>"' from UTF-8 to ASCII-8BIT`

If I remove the degree symbol it will come up for other characters (e.g. divide symbol).

Rubinius Version Output: `rubinius 2.0.0.rc1 (1.9.3 1dd2e999 yyyy-mm-dd JI) [x86_64-apple-darwin12.2.1]`

Stack Trace:

``````
       undefined conversion for '"<p>On a very cold morning, it was -8°F. As the day went on, the temperature rose 2 degrees each hour. Which equation shows the temperature over time?</p>"' from UTF-8 to ASCII-8BIT
        kernel/common/type19.rb:163:in `compatible_encoding'
        kernel/common/string19.rb:984:in `[]='
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/sanitize-2.0.3/lib/sanitize.rb:116:in `clean!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/sanitize-2.0.3/lib/sanitize.rb:93:in `clean'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/sanitize-2.0.3/lib/sanitize.rb:53:in `clean'
        /Users/scottshea/source/apangea/app/models/item_step.rb:261:in `sanitize_fields'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:407:in `_run__4576462958671723974__save__1338411874204908663__callbacks'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/callbacks.rb:264:in `create_or_update'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/persistence.rb:104:in `save!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/validations.rb:56:in `save!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:264:in `save!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:25:in `transaction_with_transactional_fixtures'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction_without_transactional_fixtures (transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:23:in `transaction (transaction_with_transactional_fixtures)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/connection_proxy.rb:24:in `transaction (method_missing)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/sharding/stub_connection.rb:71:in `transaction (method_missing)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction_without_trace_ActiveRecord_self_name_transaction (transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:491:in `transaction_with_trace_ActiveRecord_self_name_transaction'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:486:in `transaction (transaction_with_trace_ActiveRecord_self_name_transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:264:in `save!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/has_many_association.rb:14:in `insert_record'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:436:in `create_record'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:344:in `add_to_target'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:434:in `create_record'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:149:in `transaction'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:25:in `transaction_with_transactional_fixtures'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction_without_transactional_fixtures (transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:23:in `transaction (transaction_with_transactional_fixtures)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/connection_proxy.rb:24:in `transaction (method_missing)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/sharding/stub_connection.rb:71:in `transaction (method_missing)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction_without_trace_ActiveRecord_self_name_transaction (transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:491:in `transaction_with_trace_ActiveRecord_self_name_transaction'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/newrelic_rpm-3.5.6.55/lib/new_relic/agent/method_tracer.rb:486:in `transaction (transaction_with_trace_ActiveRecord_self_name_transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:148:in `transaction'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:433:in `create_record'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:123:in `create!'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/associations/collection_proxy.rb:46:in `create!'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:268:in `process_item_steps'
        kernel/common/enumerable19.rb:137:in `each_with_index'
        kernel/bootstrap/array.rb:68:in `each'
        kernel/common/enumerable19.rb:136:in `each_with_index'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:266:in `process_item_steps'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:248:in `process_items'
        kernel/common/enumerable19.rb:137:in `each_with_index'
        kernel/bootstrap/array.rb:68:in `each'
        kernel/common/enumerable19.rb:136:in `each_with_index'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:234:in `process_items'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:227:in `process_activities'
        kernel/common/enumerable19.rb:137:in `each_with_index'
        kernel/bootstrap/array.rb:68:in `each'
        kernel/common/enumerable19.rb:136:in `each_with_index'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:208:in `process_activities'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:161:in `do_execute'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:25:in `transaction_with_transactional_fixtures'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction_without_transactional_fixtures (transaction)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/gems/test_after_commit-0.0.1/lib/test_after_commit.rb:23:in `transaction (transaction_with_transactional_fixtures)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/connection_proxy.rb:24:in `transaction (method_missing)'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/sharding/stub_connection.rb:71:in `transaction (method_missing)'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:145:in `do_execute'
        kernel/common/enumerable19.rb:137:in `each_with_index'
        kernel/bootstrap/array.rb:68:in `each'
        kernel/common/enumerable19.rb:136:in `each_with_index'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:141:in `do_execute'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:91:in `execute'
        /Users/scottshea/.rvm/gems/rbx-head@ttm/bundler/gems/db-charmer-ca1a14c3f01d/lib/db_charmer/active_record/multi_db_proxy.rb:41:in `on_db'
        /Users/scottshea/source/apangea/test/fixtures/pathways/pathway_loader.rb:91:in `execute'
        /Users/scottshea/source/apangea/test/test_helper.rb:100:in `load_pathway'
        /Users/scottshea/source/apangea/test/unit/enrollment_test.rb:275:in `__script__'```
``````

**Comment by brauliobo** [comment]
I'm getting `undefined conversion for 'xxx' from UTF-8 to ASCII-8BIT` for all rails erb templates with utf-8 characters

Using version 2.5.2.

**Comment by YorickPeterse** [comment]
@brauliobo Please submit a new issue for that instead of necro-ing an existing one. Please also include a full stack trace and if possible a way to reproduce the problem.
