### ISSUE TITLE
[rails] (ArgumentError) "comparison of #<Enumerable::SortedElement:0xcf8ec..failed (6)

### ISSUE THREAD

**Issue by masterkain** [rubinius/rubinius#2243]
Hello,
trying to run `rbx-head --1.9` against my project.

`Running in rubinius 2.0.0.rc1 (1.9.3 1c56f6a9 yyyy-mm-dd JI) [x86_64-apple-darwin12.3.0]`

On a batch of around 400 records to save (in parallel, using sidekiq), in one I got this during a plain `save` (new record):

```
An ArgumentError occurred in background at 2013-03-28 06:36:58 UTC :

  comparison of #<Enumerable::SortedElement:0xcf8ec @sort_id="type" @value=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x76558 @columns=nil @table_alias=nil @primary_key=nil @aliases=[] @name="media_files" @engine=AudioFile(id: integer, [....], composer: string)>, name="type">, "AudioFile"]> with #<Enumerable::SortedElement:0xcf924 @sort_id=nil @value=[#<struct Arel::Attributes::Attribute relation=nil, name=nil>, "He Who Breeds Pestilence"]> failed (6)
  kernel/common/array.rb:1220:in `isort!'
```

Slightly edited the number of fields in model with `[...]`.

```
  kernel/common/array.rb:1220:in `isort!'
  kernel/common/array.rb:1098:in `mergesort!'
  kernel/common/array.rb:909:in `sort! (sort_inplace)'
  kernel/common/enumerable.rb:58:in `sort_by'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/relation.rb:51:in `insert'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/persistence.rb:367:in `create'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/timestamp.rb:58:in `create'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `create'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:414:in `_run__2374303270957259956__create__1338411874204908663__callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `create'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/persistence.rb:348:in `create_or_update'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:436:in `_run__2374303270957259956__save__1338411874204908663__callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/persistence.rb:84:in `save'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/validations.rb:50:in `save'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/attribute_methods/dirty.rb:22:in `save'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `save'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction_without_trace_ActiveRecord_self_name_transaction (transaction)'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/newrelic_rpm-3.6.0.78/lib/new_relic/agent/method_tracer.rb:486:in `transaction_with_trace_ActiveRecord_self_name_transaction'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/newrelic_rpm-3.6.0.78/lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/newrelic_rpm-3.6.0.78/lib/new_relic/agent/method_tracer.rb:481:in `transaction (transaction_with_trace_ActiveRecord_self_name_transaction)'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `save'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
  /Users/kain/.rvm/gems/rbx-head@mygemset/gems/activerecord-3.2.12/lib/active_record/transactions.rb:258:in `save'
```

I'm not sure it helps a great deal but here it is.

**Comment by YorickPeterse** [comment]
Any update on this?

**Comment by YorickPeterse** [comment]
Closing this due to the lack of feedback or a way to reproduce this problem. If this issue still persists on the latest version of Rubinius feel free to re-open.
