### ISSUE TITLE
SyntaxError: invalid multibyte char (UTF-8)

### ISSUE THREAD

**Issue by pyromaniac** [rubinius/rubinius#2394]
Simple case, but I've got an exception

```
guard-mac:~ pyromaniac$ irb
1.9.3p429 :001 > "при\вет"
 => "привет"
1.9.3p429 :002 >
guard-mac:~ pyromaniac$ rvm use rbx
Using /Users/pyromaniac/.rvm/gems/rbx-head
guard-mac:~ pyromaniac$ irb
rubinius-2.0.0.rc1 :001 > "при\вет"
SyntaxError: invalid multibyte char (UTF-8)
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/melbourne.rbc:81:in `syntax_error'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/melbourne.rbc:88:in `parse_string'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/compiler/stages.rbc:241:in `parse'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/compiler/stages.rbc:207:in `run'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/compiler/compiler.rbc:374:in `run'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/compiler/compiler.rbc:302:in `compile_eval'
    from /Users/pyromaniac/.rvm/rubies/rbx-head/runtime/19/compiler/compiler.rbc:314:in `construct_block'
    from kernel/common/eval.rb:70:in `eval'
    from kernel/common/kernel19.rb:42:in `loop'
    from kernel/common/throw_catch19.rb:8:in `catch'
    from kernel/common/throw_catch.rb:10:in `register'
    from kernel/common/throw_catch19.rb:7:in `catch'
    from kernel/common/throw_catch19.rb:8:in `catch'
    from kernel/common/throw_catch.rb:10:in `register'
    from kernel/common/throw_catch19.rb:7:in `catch'
    from kernel/delta/codeloader.rb:68:in `load_script'
    from kernel/delta/codeloader.rb:118:in `load_script'
    from kernel/loader.rb:615:in `script'
    from kernel/loader.rb:816:in `main'rubinius-2.0.0.rc1 :002 >
```

Thanx for your work.

**Comment by jjb** [comment]
I am experiencing this bug with 2.5.2. With this test script:

```ruby
"".gsub(/\•/, "")
```
I get this behavior:

```console
➔ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
➔ ruby bug.rb   
➔ rbenv shell rbx-2.5.2 
➔ ruby --version       
rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.5.1 JI) [x86_64-darwin14.1.0]
➔ ruby bug.rb          
A syntax error has occurred:
    invalid multibyte char (UTF-8): /Users/john/tmp/bug.rb:1:12

Code:
"".gsub(/\•/, "")
           ^

Backtrace:

    CodeTools::Melbourne#syntax_error at /Users/john/.rbenv/versions/rbx-2.5.2
                                         /runtime/gems
                                         /rubinius-melbourne-2.3.1.0/lib
                                         /rubinius/melbourne.rbc:48
      CodeTools::Melbourne#parse_file at /Users/john/.rbenv/versions/rbx-2.5.2
                                         /runtime/gems
                                         /rubinius-melbourne-2.3.1.0/lib
                                         /rubinius/melbourne.rbc:61
 CodeTools::Compiler::FileParser#parse at /Users/john/.rbenv/versions/rbx-2.5.2
                                          /runtime/gems/rubinius-compiler-2.3.1
                                          /lib/rubinius/compiler/stages.rbc:225
  CodeTools::Compiler::Parser(CodeTools::Compiler::FileParser)#run at \
          /Users/john/.rbenv/versions/rbx-2.5.2/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/stages.rbc:207
              CodeTools::Compiler#run at /Users/john/.rbenv/versions/rbx-2.5.2
                                         /runtime/gems/rubinius-compiler-2.3.1
                                         /lib/rubinius/compiler/compiler.rbc:359
          CodeTools::Compiler.compile at /Users/john/.rbenv/versions/rbx-2.5.2
                                         /runtime/gems/rubinius-compiler-2.3.1
                                         /lib/rubinius/compiler/compiler.rbc:89
     Rubinius::CodeLoader#compile_file at kernel/delta/code_loader.rb:217
        Rubinius::CodeLoader#load_file at kernel/delta/code_loader.rb:190
      Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:62
      Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
               Rubinius::Loader#script at kernel/loader.rb:655
                 Rubinius::Loader#main at kernel/loader.rb:809
```

**Comment by YorickPeterse** [comment]
@jjb Could you report that as a separate issue? While the error is the same I have my doubts about the actual cause being the same.

**Comment by jjb** [comment]
@YorickPeterse done! https://github.com/rubinius/rubinius/issues/3370
