### ISSUE TITLE
gem install error on rbx-2.2.5

### ISSUE THREAD

**Issue by mpapis** [rubinius/rubinius#2929]
$`ruby -wdS gem install haml`

``` bash
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- rubygems/defaults/operating_system
Exception: `NoMethodError' /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/config_file.rb:63 - undefined method `sysconfdir' on Etc (Module)
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- Win32API
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- Win32API
Exception: `NameError' /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/config_file.rb:325 - Missing or uninitialized constant: Gem::ConfigFile::Psych
Exception: `Gem::LoadError' /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency.rb:309 - Could not find 'psych' (>= 1.2.1, ~> 1.2) among 103 total gem(s)
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- psych
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- psych
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- psych
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- psych
Exception: `NameError' kernel/bootstrap/array.rb:66 - method `yaml_as' not defined in Module
Exception: `NameError' kernel/common/module.rb:347 - undefined method `to_yaml_properties' for Object
Exception: `NameError' /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/syck_hack.rb:20 - Missing or uninitialized constant: Syck::Syck
Exception: `NameError' kernel/bootstrap/array.rb:66 - method `to_s' not defined in Syck::DefaultKey
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- etc.so
Exception: `LoadError' kernel/common/code_loader.rb:431 - no such file to load -- etc.so
Exception: `NoMethodError' kernel/common/type.rb:24 - undefined method `to_str' on spec:Symbol.
Exception: `TypeError' kernel/common/type.rb:19 - Coercion error: :spec.to_str => String failed
Exception: `NoMethodError' kernel/common/type.rb:24 - undefined method `to_str' on path:Symbol.
Exception: `TypeError' kernel/common/type.rb:19 - Coercion error: :path.to_str => String failed
Exception: `NoMethodError' kernel/common/type.rb:24 - undefined method `to_str' on value:Symbol.
Exception: `TypeError' kernel/common/type.rb:19 - Coercion error: :value.to_str => String failed
Exception: `NoMethodError' kernel/common/type.rb:24 - undefined method `to_str' on needed:Symbol.
Exception: `TypeError' kernel/common/type.rb:19 - Coercion error: :needed.to_str => String failed
Exception: `Resolv::ResolvTimeout' /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:521 - Resolv::ResolvTimeout
Exception: `Errno::EINVAL' /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:1321 - Invalid argument - connect(2)
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - connect(2)
        kernel/common/errno.rb:17:in `handle'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:1321:in `connect'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:1328:in `send'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:768:in `send'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:662:in `request'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:521:in `each_resource'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:1055:in `resolv'
        kernel/bootstrap/array.rb:66:in `each'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:1053:in `resolv'
        kernel/bootstrap/array.rb:66:in `each'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:1052:in `resolv'
        kernel/bootstrap/array.rb:66:in `each'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:1050:in `resolv'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:513:in `each_resource'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-resolv-2.0.0/lib/rubysl/resolv/resolv.rb:490:in `getresource'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/remote_fetcher.rb:88:in `api_endpoint'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/source.rb:42:in `api_uri'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/source.rb:170:in `load_specs'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/spec_fetcher.rb:266:in `tuples_for'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/spec_fetcher.rb:226:in `available_specs'
        kernel/bootstrap/array.rb:66:in `each'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/source_list.rb:97:in `each_source'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/spec_fetcher.rb:222:in `available_specs'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/spec_fetcher.rb:102:in `search_for_dependency'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency_installer.rb:216:in `find_gems_with_sources'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency_installer.rb:292:in `find_spec_by_name_and_version'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency_installer.rb:166:in `available_set_for'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency_installer.rb:418:in `resolve_dependencies'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/dependency_installer.rb:371:in `install'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/commands/install_command.rb:219:in `install_gem'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/commands/install_command.rb:263:in `install_gems'
        kernel/bootstrap/array.rb:66:in `each'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/commands/install_command.rb:259:in `install_gems'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/commands/install_command.rb:171:in `execute'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/command.rb:305:in `invoke_with_build_args'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/command_manager.rb:167:in `process_args'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/command_manager.rb:137:in `run'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/gem_runner.rb:54:in `run'
        /home/mpapis/.rvm/rubies/rbx-2.2.5/library/bin/gem.rb:21:in `__script__'
        kernel/delta/code_loader.rb:66:in `load_script'
        kernel/delta/code_loader.rb:152:in `load_script'
        kernel/loader.rb:649:in `script'
        kernel/loader.rb:831:in `main'
Exception: `Gem::SystemExitException' /home/mpapis/.rvm/rubies/rbx-2.2.5/site/rubygems/user_interaction.rb:158 - Exiting RubyGems with exit_code 1
Exception: `SystemExit' kernel/common/kernel.rb:265 - SystemExit
```

**Comment by brixen** [comment]
Please open a new issue if this fails on the current Rubinius release.
