### ISSUE TITLE
Error raised by Regexp.new(<integer>) differs between MRI and Rubinius

### ISSUE THREAD

**Issue by limhoff-r7** [rubinius/rubinius#2959]
In MRI 1.9.3-p545:

```irb
1.9.3-p545 :001 > Regexp.new(123)
TypeError: can't convert Fixnum into String
```

In Rubinius 2.2.5:

```irb
rbx-2.2.5 :001 > Regexp.new(123)
PrimitiveFailure: Regexp.compile(123, 0) primitive failed
	from kernel/bootstrap/regexp.rb:13:in `compile'
	from kernel/common/regexp.rb:141:in `initialize'
	from (irb):1
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:460:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:649:in `script'
	from kernel/loader.rb:831:in `main'rbx-2.2.5 :002
```

This causes issues in https://github.com/limhoff-r7/metasploit-framework/blob/3d196cb399bb9a711427916d38c43cb3779624ae/lib/msf/core/option_container.rb#L485-L491 as I can't rescue PrimiteFailure since it's Rubinius specific.  

Should Regexp.new raising TypeError when passed an Integer be in RubySpec or is this considered implementation-specific behavior?

**Comment by YorickPeterse** [comment]
This still occurs as of 4417909e57f781fc14f6dda55964c5f34696f9c2.

**Comment by jemc** [comment]
Looks like @jc00ke's two commits somehow got reverted.  If reapplied, they should fix this.
