### ISSUE TITLE
Possible bug in behavior of sort!

### ISSUE THREAD

**Issue by bf4** [rubinius/rubinius#3050]
While testing the mail gem, all travis builds fail against rbx-2, and previous to that rbx-18mode and rbx-19mode.

https://travis-ci.org/mikel/mail/jobs/26092400

example

``` plain
 1) Attachments decoding and encoding should set its content_transfer_encoding
     Failure/Error: @mail.ready_to_send!
     ArgumentError:
       method 'sort!': given 0, expected 1
     # kernel/common/enumerable.rb:260:in `sort_by'
     # ./lib/mail/parts_list.rb:36:in `sort!'
     # ./lib/mail/message.rb:1784:in `ready_to_send!'
     # ./spec/mail/attachments_list_spec.rb:80:in `__script__'
     # kernel/common/eval.rb:43:in `instance_eval'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `run_examples'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `autorun'
     # kernel/bootstrap/proc.rb:20:in `call'
     # kernel/loader.rb:710:in `run_at_exits'
     # kernel/loader.rb:730:in `epilogue'
     # kernel/loader.rb:866:in `main'
```

``` plain
17) Test emails from the wild raw_email_encoded_stack_level_too_deep.eml should return an 'encoded' version without raising a SystemStackError
     Failure/Error: doing { @message.encoded }.should_not raise_error
       expected no Exception, got #<ArgumentError: method 'sort!': given 0, expected 1> with backtrace:
         # kernel/common/enumerable.rb:260:in `sort_by'
         # ./lib/mail/parts_list.rb:36:in `sort!'
         # ./lib/mail/message.rb:1784:in `ready_to_send!'
         # ./lib/mail/message.rb:1801:in `encoded'
         # ./spec/mail/example_emails_spec.rb:270:in `__script__'
         # kernel/bootstrap/proc.rb:20:in `call'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/matchers/built_in/raise_error.rb:22:in `matches?'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/matchers/built_in/raise_error.rb:41:in `does_not_match?'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/expectations/handler.rb:46:in `handle_matcher'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/expectations/syntax.rb:57:in `should_not'
         # ./spec/mail/example_emails_spec.rb:270:in `__script__'
         # kernel/common/eval.rb:43:in `instance_eval'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `run_examples'
         # kernel/bootstrap/array.rb:87:in `map'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
         # kernel/bootstrap/array.rb:87:in `map'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
         # kernel/bootstrap/array.rb:87:in `map'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
         # kernel/bootstrap/array.rb:87:in `map'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
         # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `autorun'
         # kernel/bootstrap/proc.rb:20:in `call'
         # kernel/loader.rb:710:in `run_at_exits'
         # kernel/loader.rb:730:in `epilogue'
         # kernel/loader.rb:866:in `main'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:33:in `fail_with'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/expectations/handler.rb:57:in `handle_matcher'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-expectations-2.12.1/lib/rspec/expectations/syntax.rb:57:in `should_not'
     # ./spec/mail/example_emails_spec.rb:270:in `__script__'
     # kernel/common/eval.rb:43:in `instance_eval'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `run_examples'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
     # kernel/bootstrap/array.rb:87:in `map'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
     # ./gemfiles/vendor/bundle/rbx/2.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `autorun'
     # kernel/bootstrap/proc.rb:20:in `call'
     # kernel/loader.rb:710:in `run_at_exits'
     # kernel/loader.rb:730:in `epilogue'
     # kernel/loader.rb:866:in `main'
```

Since Jan 2013 it appears https://github.com/mikel/mail/commit/cae68382ce67f5506889f4abadccdcb366e0ff25#diff-354f30a63fb0907d4ad57269548329e3

**Comment by BenMorganIO** [comment]
Hey, I'd like to bump this thread.

I'm currently trying to get spree/spree to run with Rubinius I'm getting some failures. Most are due to the issue being discussed here. The specs can viewed in [CircleCI](https://circleci.com/gh/BenMorganIO/spree/9).

**Comment by bf4** [comment]
@BenMorganIO not sure if you read this thread, but this issue was mail-gem-specific, and resolved in https://github.com/mikel/mail/pull/782 as indicated above.  It might not yet be in a released gem.
