### ISSUE TITLE
Rubinius::ObjectBoundsExceededError in products # landing_page

### ISSUE THREAD

**Issue by emptyflask** [rubinius/rubinius#3095]
I've been getting this occasionally right after deployments to a multithreaded puma environment. Since I can't duplicate it reliably, I assume it's related to threads, but I really have no idea what's going on.

```
Rubinius::ObjectBoundsExceededError in products # landing_page

ActionView::Template::Error (Tuple::at_prim: index 16 out of bounds for size 16):
    1: %footer
    2:   .row.text-center
    3:     = cache "footer/products/conf_links" do
    4:       = render 'products/conf_links'
    5:
    6:     .medium-10.small-centered.columns
    7:       %p
  app/views/layouts/_footer.haml:4:in `_app_views_layouts__footer_haml__4150224644170444963_517112'
  app/views/layouts/_footer.haml:3:in `_app_views_layouts__footer_haml__4150224644170444963_517112'
  app/views/layouts/application.html.haml:30:in `_app_views_layouts_application_html_haml__3537268695073671881_399340'
```

The rest of it from Honeybadger:

```
kernel/common/hash.rb:462:in `redistribute`
kernel/common/hash.rb:191:in `[]=`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template/resolver.rb:36:in `initialize`
kernel/bootstrap/proc.rb:20:in `call`
kernel/common/hash.rb:274:in `default`
kernel/common/hash.rb:619:in `[]`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template/resolver.rb:75:in `cached`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template/resolver.rb:45:in `find_all`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/path_set.rb:65:in `find_all`
kernel/bootstrap/array.rb:76:in `each`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/path_set.rb:64:in `find_all`
kernel/bootstrap/array.rb:76:in `each`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/path_set.rb:63:in `find_all`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/path_set.rb:58:in `find`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/lookup_context.rb:122:in `find_template (find)`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:339:in `find_template`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:333:in `find_partial`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:222:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:41:in `render_partial`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/helpers/rendering_helper.rb:27:in `render_without_haml (render)`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers.rb:89:in `non_haml`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `render (render_with_haml)`
[PROJECT_ROOT]/app/views/layouts/_footer.haml:4:in `_app_views_layouts__footer_haml__4150224644170444963_517112`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/helpers/cache_helper.rb:53:in `fragment_for`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/helpers/cache_helper.rb:36:in `cache`
[PROJECT_ROOT]/app/views/layouts/_footer.haml:3:in `_app_views_layouts__footer_haml__4150224644170444963_517112`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `render`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:238:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/partial_renderer.rb:237:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:41:in `render_partial`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/helpers/rendering_helper.rb:27:in `render_without_haml (render)`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers.rb:89:in `non_haml`
[GEM_ROOT]/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `render (render_with_haml)`
[PROJECT_ROOT]/app/views/layouts/application.html.haml:30:in `_app_views_layouts_application_html_haml__3537268695073671881_399340`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `render`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:45:in `render_template`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:18:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:36:in `render_template`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:17:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:110:in `_render_template`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/streaming.rb:225:in `_render_template`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:103:in `render_to_body`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/renderers.rb:28:in `render_to_body`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/compatibility.rb:50:in `render_to_body`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:88:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:16:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `render`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms`
/home/app/.rubies/rbx-2.2.9/gems/gems/rubysl-benchmark-2.0.1/lib/rubysl/benchmark/benchmark.rb:294:in `realtime`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime`
[GEM_ROOT]/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:39:in `render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:10:in `default_render`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:5:in `send_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `process_action`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:447:in `_run__1198746526351415222__process_action__104242844507077691__callbacks`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `process_action`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action`
[GEM_ROOT]/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `action`
kernel/bootstrap/proc.rb:20:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call`
[GEM_ROOT]/gems/journey-1.0.4/lib/journey/router.rb:68:in `call`
kernel/bootstrap/array.rb:76:in `each`
[GEM_ROOT]/gems/journey-1.0.4/lib/journey/router.rb:56:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call`
[GEM_ROOT]/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!`
[GEM_ROOT]/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call`
[GEM_ROOT]/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call`
[GEM_ROOT]/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call`
[GEM_ROOT]/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `call`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__2705956171196396203__call__1338411874204908663__callbacks`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/sendfile.rb:102:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/tagged_logging.rb:22:in `tagged`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call`
[GEM_ROOT]/gems/actionpack-3.2.19/lib/action_dispatch/middleware/request_id.rb:22:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call`
[GEM_ROOT]/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call`
[GEM_ROOT]/gems/activesupport-3.2.19/lib/active_support/cache/strategy/local_cache.rb:72:in `call`
[GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward`
[GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch`
[GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup`
[GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!`
[GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/application.rb:231:in `call`
[GEM_ROOT]/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `call (method_missing)`
[GEM_ROOT]/gems/puma-2.9.0/lib/puma/configuration.rb:71:in `call`
[GEM_ROOT]/gems/puma-2.9.0/lib/puma/server.rb:490:in `handle_request`
[GEM_ROOT]/gems/puma-2.9.0/lib/puma/server.rb:361:in `process_client`
[GEM_ROOT]/gems/puma-2.9.0/lib/puma/server.rb:254:in `run`
kernel/bootstrap/proc.rb:20:in `call`
[GEM_ROOT]/gems/puma-2.9.0/lib/puma/thread_pool.rb:92:in `spawn_thread`
kernel/bootstrap/proc.rb:20:in `call`
kernel/bootstrap/thread.rb:391:in `__run__`
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
