### ISSUE TITLE
undefined method `block_env' on an instance of Rubinius::CompiledCode

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#3118]
```
E, [2014-08-30T21:15:55.601407 #75353] ERROR -- : undefined method `block_env' on an instance of Rubinius::CompiledCode. (NoMethodError)                                                       
kernel/delta/kernel.rb:78:in `block_env (method_missing)'                                                                                                                                      
kernel/common/block_environment.rb:114:in `=='                                                                                                                                                 
kernel/common/method.rb:41:in `=='                                                                                                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/lib/rainbows/http_server.rb:45:in `worker_loop'                                                                                      
kernel/common/method.rb:71:in `call'                                                                                                                                                           
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/rainbows_instrumentation.rb:22:in `__script__'                                           
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/lib/rainbows/http_server.rb:61:in `spawn_missing_workers'                                                                            
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'                                                                                              
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/bin/rainbows:127:in `__script__'                                                                                                     
kernel/common/kernel.rb:447:in `load'                                                                                                                                                          
/home/ghazel/.rvm/gems/rbx-2.2.10/bin/rainbows:23:in `__script__'                                                                                                                          
kernel/common/block_environment.rb:53:in `call_on_instance'                                                                                                                                    
kernel/common/eval.rb:176:in `eval'                                                                                                                                                            
/home/ghazel/.rvm/gems/rbx-2.2.10/bin/ruby_executable_hooks:15:in `__script__'                                                                                                             
kernel/delta/code_loader.rb:66:in `load_script'                                                                                                                                                
kernel/delta/code_loader.rb:152:in `load_script'                                                                                                                                               
kernel/loader.rb:649:in `script'                                                                                                                                                               
kernel/loader.rb:825:in `main'
```

**Comment by tak1n** [comment]
Using this works:

```ruby
File.write 'config.ru', <<-EOS
require 'sinatra/base'
class Foo < Sinatra::Base
end
run Foo
EOS
Rainbows! do
  use :ThreadPool
  worker_connections 2
end
listen 0
preload_app true
```
Just omitted the newrelic_rpm require.
Need to dig deeper into newrelic_rpm gem to know whats causing this.

**Comment by tak1n** [comment]
Without `newrelic_rpm` inserting a binding.pry in https://github.com/godfat/rainbows/blob/master/lib/rainbows/http_server.rb#L40 and doing some spiking has following results:

```
rubinius-bugs ➤ rainbows -c rainbows.rb                                                                                                                                                                git:master*
I, [2015-05-24T00:21:26.257744 #14000]  INFO -- : Refreshing Gem list
I, [2015-05-24T00:21:26.446761 #14000]  INFO -- : listening on addr=0.0.0.0:50651 fd=9
I, [2015-05-24T00:21:26.447141 #14000]  INFO -- : worker=0 spawning...
I, [2015-05-24T00:21:26.448398 #14000]  INFO -- : master process ready

From: /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/rainbows-4.6.2/lib/rainbows/http_server.rb @ line 46 Rainbows::HttpServer#worker_loop:

    40: def worker_loop(worker)
    41:   Rainbows.forked = true
    42:   orig = method(:worker_loop)
    43:   extend(Rainbows.const_get(@use))
    44:   m = method(:worker_loop)
    45:   require 'pry'
 => 46:   binding.pry
    47:   orig == m ? super(worker) : worker_loop(worker)
    48: end

[1] pry(#<Rainbows::HttpServer>)> orig
=> #<Method: Rainbows::HttpServer#worker_loop (defined in Rainbows::HttpServer at /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/rainbows-4.6.2/lib/rainbows/http_server.rb:40)>
[2] pry(#<Rainbows::HttpServer>)> m
=> #<Method: Rainbows::HttpServer#worker_loop (defined in Rainbows::ThreadPool at /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/rainbows-4.6.2/lib/rainbows/thread_pool.rb:22)>
[3] pry(#<Rainbows::HttpServer>)> orig == m
=> false
[4] pry(#<Rainbows::HttpServer>)> m == orig
=> false
```

With `newrelic_rpm` required:

```
rubinius-bugs ➤ rainbows -c rainbows.rb                                                                                                                                                                git:master*
I, [2015-05-24T00:24:03.530713 #14294]  INFO -- : Refreshing Gem list
I, [2015-05-24T00:24:03.968098 #14294]  INFO -- : listening on addr=0.0.0.0:38466 fd=10
I, [2015-05-24T00:24:03.968521 #14294]  INFO -- : worker=0 spawning...
I, [2015-05-24T00:24:03.969969 #14294]  INFO -- : master process ready

From: /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/rainbows-4.6.2/lib/rainbows/http_server.rb @ line 46 Rainbows::ThreadPool#worker_loop:

    41:     Rainbows.forked = true
    42:     orig = method(:worker_loop)
    43:     extend(Rainbows.const_get(@use))
    44:     m = method(:worker_loop)
    45:     require 'pry'
 => 46:     binding.pry
    47:     orig == m ? super(worker) : worker_loop(worker)
    48:   end
    49: 
    50:   def spawn_missing_workers
    51:     # 5: std{in,out,err} + heartbeat FD + per-process listener

[1] pry(#<Rainbows::HttpServer>)> orig
=> #<Method: Rainbows::HttpServer#worker_loop (defined in Rainbows::HttpServer at /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/rainbows_instrumentation.rb:20)>
[2] pry(#<Rainbows::HttpServer>)> m
=> #<Method: Rainbows::HttpServer#worker_loop (defined in Rainbows::ThreadPool at /home/benny/Development/ruby/learn/rubinius-bugs/.gem/rbx/2.1.0/gems/rainbows-4.6.2/lib/rainbows/thread_pool.rb:22)>
[3] pry(#<Rainbows::HttpServer>)> orig == m
NoMethodError: undefined method `block_env' on an instance of Rubinius::CompiledCode.
from kernel/delta/kernel.rb:78:in `block_env (method_missing)'
[4] pry(#<Rainbows::HttpServer>)> m == orig
=> false
```

**Comment by tak1n** [comment]
With the patch in #3407 applied I get following result:

```
rubinius-bugs ➤ rainbows -c rainbows.rb                                                                                                                                                                git:master*
I, [2015-05-24T09:49:52.674181 #8456]  INFO -- : Refreshing Gem list
I, [2015-05-24T09:49:53.109024 #8456]  INFO -- : listening on addr=0.0.0.0:41283 fd=10
I, [2015-05-24T09:49:53.109458 #8456]  INFO -- : worker=0 spawning...
I, [2015-05-24T09:49:53.111144 #8456]  INFO -- : master process ready
I, [2015-05-24T09:49:53.127331 #8464]  INFO -- : worker=0 spawned pid=8464
I, [2015-05-24T09:49:53.364228 #8464]  INFO -- : Rainbows! ThreadPool worker_connections=2
```
