### ISSUE TITLE
rand bugs with ranges

### ISSUE THREAD

**Issue by fengb** [rubinius/rubinius#3180]
On MRI 2.1.4:

```
irb(main):001:0> rand(1.0..1.0)
=> 1.0
irb(main):002:0> rand(1..0)
=> nil
irb(main):003:0> rand(BigDecimal(0.01, 2)..BigDecimal(1, 2))
=> #<BigDecimal:7f966c0f1180,'0.1E-1',9(36)>
```

On Rubinius 2.3.0:

```
irb(main):001:0> rand(1.0..1.0)
ArgumentError: invalid argument - 0.0
    from kernel/common/random.rb:39:in `random'
    from kernel/common/random.rb:72:in `random_range'
    from kernel/common/random.rb:36:in `random'
    from kernel/common/kernel.rb:687:in `rand'
irb(main):002:0> rand(1..0)
NoMethodError: undefined method `coerce' on nil:NilClass.
    from kernel/delta/kernel.rb:78:in `coerce (method_missing)'
    from kernel/common/random.rb:69:in `random_range'
    from kernel/common/random.rb:36:in `random'
    from kernel/common/kernel.rb:687:in `rand'
irb(main):003:0> rand(BigDecimal(0.01, 2)..BigDecimal(1, 2))
ArgumentError: invalid argument - 0.99E0
    from kernel/common/random.rb:43:in `random'
    from kernel/common/random.rb:72:in `random_range'
    from kernel/common/random.rb:36:in `random'
    from kernel/common/kernel.rb:687:in `rand'
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
