### ISSUE TITLE
Install 2.4.1 on Ubuntu fails with gcc

### ISSUE THREAD

**Issue by burningTyger** [rubinius/rubinius#3232]
As issued at rvm (https://github.com/wayneeseguin/rvm/pull/3182) I get a compile error which can be resolved by compiling rbx with clang-3.4.

Since this is vanilla rbx I'll post the `rake` output only:

```
2: CXX vm/machine_code.cpp
2: CXX vm/marshal.cpp
2: CXX vm/method_primitives.cpp
{standard input}: Assembler messages:
{standard input}:260820: Warning: end of file not at end of a line; newline inserted
{standard input}:261906: Error: unknown pseudo-op: `.s'
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Error: g++ -I/home/user/rubinius/vm -I/home/user/rubinius/vm/include -I/home/user/rubinius/vm/builtin -I. -Ivm/test/cxxtest -I/home/user/rub
inius/vendor/udis86 -I/home/user/rubinius/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/home/user/rubinius/vm/includ
e/capi -I/home/user/rubinius/vendor/oniguruma -I/home/user/rubinius/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g  -Wno-unused-resu
lt -fPIC  -O2 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DH
AVE_INOTIFY -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHA
VE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -DSTRERROR_R_CHAR_P -I/usr/lib/llvm-3.4/include -I/usr/lib/llvm-3.4/include -D
_GNU_SOURCE -g -fPIC -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURC
E -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden  -Wno-unused-result    -c -o vm/artifacts/method_primitives.cpp.o vm/method_primi
tives.cpp
rake aborted!
Error compiling
/home/user/.rvm/gems/rbx-2.3.0/gems/daedalus-core-0.1.0/lib/daedalus.rb:68:in `command'
/home/user/.rvm/gems/rbx-2.3.0/gems/daedalus-core-0.1.0/lib/daedalus.rb:234:in `cxx_compile'
/home/user/.rvm/gems/rbx-2.3.0/gems/daedalus-core-0.1.0/lib/daedalus.rb:221:in `compile'
/home/user/.rvm/gems/rbx-2.3.0/gems/daedalus-core-0.1.0/lib/daedalus.rb:433:in `build'
/home/user/.rvm/gems/rbx-2.3.0/gems/daedalus-core-0.1.0/lib/daedalus.rb:895:in `perform_tasks'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/thread.rb:391:in `__run__'
Tasks: TOP => default => spec => build => build:build => vm/vm
(See full trace by running task with --trace)
```

For more details check rvm issue.

**Comment by tak1n** [comment]
Are you bound to the version 2.4.1?
If not please close this ticket and open a new one when having problems with the latest rbx.

**Comment by burningTyger** [comment]
ok, thanks for noting.
