### ISSUE TITLE
Assertion failure in JITVisit

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#3249]
rubinius 2.4.1

```
#0  0x00007f9e0cb2dbe9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f9e0cb2efe8 in __GI_abort () at abort.c:90
#2  0x00007f9e0cb26d26 in __assert_fail_base (fmt=0x7f9e0cc5cf08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x1176c28 "Val && \"isa<> used on a null pointer\"", 
    file=file@entry=0x1176b50 "/usr/include/llvm/Support/Casting.h", line=line@entry=95, 
    function=function@entry=0x11782a0 <llvm::isa_impl_cl<llvm::Constant, llvm::Value const*>::doit(llvm::Value const*)::__PRETTY_FUNCTION__> "static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::Constant; From = llvm::Value]") at assert.c:92
#3  0x00007f9e0cb26dd2 in __GI___assert_fail (assertion=0x1176c28 "Val && \"isa<> used on a null pointer\"", file=0x1176b50 "/usr/include/llvm/Support/Casting.h", line=95, 
    function=0x11782a0 <llvm::isa_impl_cl<llvm::Constant, llvm::Value const*>::doit(llvm::Value const*)::__PRETTY_FUNCTION__> "static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::Constant; From = llvm::Value]") at assert.c:101
#4  0x000000000076a88c in doit (Val=0x0, Val@entry=0x5f00000000) at /usr/include/llvm/Support/Casting.h:95  
#5  doit (Val=<optimized out>) at /usr/include/llvm/Support/Casting.h:122
#6  doit (Val=<optimized out>) at /usr/include/llvm/Support/Casting.h:114
#7  isa<llvm::Constant, llvm::Value*> (Val=<synthetic pointer>) at /usr/include/llvm/Support/Casting.h:134  
#8  dyn_cast<llvm::Constant, llvm::Value> (Val=0x0, Val@entry=0x5f00000000) at /usr/include/llvm/Support/Casting.h:278
#9  llvm::IRBuilder<true, llvm::ConstantFolder, rubinius::IRBuilderInserterWithDebug>::CreateICmp (this=this@entry=0x7f9df73f8838, P=P@entry=llvm::CmpInst::ICMP_EQ, LHS=LHS@entry=0x0, 
    RHS=RHS@entry=0x7f9dfc1100a0, Name=...) at /usr/include/llvm/IR/IRBuilder.h:1323
#10 0x00000000007909c6 in CreateICmpEQ (Name=..., RHS=0x7f9dfc1100a0, LHS=0x0, this=0x7f9df73f8838) at /usr/include/llvm/IR/IRBuilder.h:1248
#11 rubinius::JITVisit::check_for_exception_then (this=this@entry=0x7f9df73f8820, val=val@entry=0x0, cont=cont@entry=0x7f9dfd9510e0, pass_top=pass_top@entry=true)
    at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:314
#12 0x0000000000790e9c in rubinius::JITVisit::check_for_exception (this=0x7f9df73f8820, val=0x0, pass_top=<optimized out>) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:384
#13 0x000000000079a24d in rubinius::JITVisit::visit_send_stack (this=this@entry=0x7f9df73f8820, which=@0x34b7680: 140315991077160, args=1)
    at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:1621
#14 0x000000000079deab in rubinius::VisitInstructions<rubinius::JITVisit>::dispatch (this=0x7f9df73f8970, ip=23) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/gen/instruction_visitors.hpp:57
#15 0x000000000079eaa0 in call (iter=..., this=0x7f9df73f87a0) at vm/llvm/jit_builder.cpp:547
#16 rubinius::jit::ControlFlowWalker::run<rubinius::jit::Walker> (this=this@entry=0x7f9df73f87c0, each=...) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/control_flow.hpp:55
#17 0x0000000000782ea9 in rubinius::jit::Builder::generate_body (this=this@entry=0x7f9df73f8c50) at vm/llvm/jit_builder.cpp:584
#18 0x000000000076724c in rubinius::Inliner::inline_generic_method (this=this@entry=0x7f9df73f9160, klass=klass@entry=0x2c5fe70, data=..., data@entry=..., defined_in=<optimized out>, 
    code=code@entry=0x7f9df6a98f20, mcode=mcode@entry=0x34b74a0, hits=hits@entry=24736) at vm/llvm/inline.cpp:639
#19 0x0000000000767e03 in rubinius::Inliner::inline_for_class (this=0x7f9df73f9160, klass=0x2c5fe70, data=..., hits=24736) at vm/llvm/inline.cpp:273
#20 0x000000000076828c in rubinius::Inliner::consider_mono (this=this@entry=0x7f9df73f9160) at vm/llvm/inline.cpp:37
#21 0x000000000079a0a3 in rubinius::JITVisit::visit_send_stack (this=this@entry=0x7f9df73f95c0, which=@0x34b7338: 140315991076376, args=1)
    at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:1591
#22 0x000000000079deab in rubinius::VisitInstructions<rubinius::JITVisit>::dispatch (this=0x7f9df73f9710, ip=26) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/gen/instruction_visitors.hpp:57
#23 0x000000000079eaa0 in call (iter=..., this=0x7f9df73f9540) at vm/llvm/jit_builder.cpp:547
#24 rubinius::jit::ControlFlowWalker::run<rubinius::jit::Walker> (this=this@entry=0x7f9df73f9560, each=...) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/control_flow.hpp:55
#25 0x0000000000782ea9 in rubinius::jit::Builder::generate_body (this=this@entry=0x7f9df73f99f0) at vm/llvm/jit_builder.cpp:584
#26 0x000000000076724c in rubinius::Inliner::inline_generic_method (this=this@entry=0x7f9df73fa070, klass=klass@entry=0x2c5fe70, data=..., data@entry=..., defined_in=<optimized out>, 
    code=code@entry=0x7f9df6a98e48, mcode=mcode@entry=0x34b7140, hits=hits@entry=24739) at vm/llvm/inline.cpp:639
#27 0x0000000000767e03 in rubinius::Inliner::inline_for_class (this=this@entry=0x7f9df73fa070, klass=0x2c5fe70, data=..., hits=24739) at vm/llvm/inline.cpp:273
#28 0x000000000076860a in rubinius::Inliner::consider_poly (this=this@entry=0x7f9df73fa070) at vm/llvm/inline.cpp:92
#29 0x0000000000799d9a in rubinius::JITVisit::visit_send_stack (this=this@entry=0x7f9df73fa4d0, which=@0x281d068: 140315989963336, args=4)
    at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:1593
#30 0x000000000079deab in rubinius::VisitInstructions<rubinius::JITVisit>::dispatch (this=0x7f9df73fa620, ip=16) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/gen/instruction_visitors.hpp:57
#31 0x000000000079eaa0 in call (iter=..., this=0x7f9df73fa450) at vm/llvm/jit_builder.cpp:547
#32 rubinius::jit::ControlFlowWalker::run<rubinius::jit::Walker> (this=this@entry=0x7f9df73fa470, each=...) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/control_flow.hpp:55
#33 0x0000000000782ea9 in rubinius::jit::Builder::generate_body (this=this@entry=0x7f9df73fa900) at vm/llvm/jit_builder.cpp:584
#34 0x000000000076724c in rubinius::Inliner::inline_generic_method (this=this@entry=0x7f9df73fae10, klass=klass@entry=0x2d3a410, data=..., data@entry=..., defined_in=<optimized out>, 
    code=code@entry=0x7f9df6a78cb0, mcode=mcode@entry=0x281cec0, hits=hits@entry=24746) at vm/llvm/inline.cpp:639
#35 0x0000000000767e03 in rubinius::Inliner::inline_for_class (this=0x7f9df73fae10, klass=0x2d3a410, data=..., hits=24746) at vm/llvm/inline.cpp:273
#36 0x000000000076828c in rubinius::Inliner::consider_mono (this=this@entry=0x7f9df73fae10) at vm/llvm/inline.cpp:37
#37 0x000000000079a0a3 in rubinius::JITVisit::visit_send_stack (this=this@entry=0x7f9df73fb270, which=@0x281ccb0: 140315991075576, args=4)
    at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/jit_visit.hpp:1591
#38 0x000000000079deab in rubinius::VisitInstructions<rubinius::JITVisit>::dispatch (this=0x7f9df73fb3c0, ip=115) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/gen/instruction_visitors.hpp:57
#39 0x000000000079eaa0 in call (iter=..., this=0x7f9df73fb1f0) at vm/llvm/jit_builder.cpp:547
#40 rubinius::jit::ControlFlowWalker::run<rubinius::jit::Walker> (this=this@entry=0x7f9df73fb210, each=...) at /home/ec2-user/.rvm/src/rbx-2.4.1/vm/llvm/control_flow.hpp:55
#41 0x0000000000782ea9 in rubinius::jit::Builder::generate_body (this=this@entry=0x7f9df73fb6c0) at vm/llvm/jit_builder.cpp:584
#42 0x00000000007a1530 in rubinius::jit::Compiler::compile_builder (this=this@entry=0x7f9df73fbb30, info=..., work=...) at vm/llvm/jit_compiler.cpp:295
#43 0x00000000007a178f in rubinius::jit::Compiler::compile_method (this=this@entry=0x7f9df73fbb30, req=0x7f9db1446620) at vm/llvm/jit_compiler.cpp:270
#44 0x00000000007a2010 in rubinius::jit::Compiler::compile (this=this@entry=0x7f9df73fbb30, req=<optimized out>) at vm/llvm/jit_compiler.cpp:158
#45 0x00000000007c0c22 in rubinius::LLVMState::perform (this=0x212fe30, state=state@entry=0x7f9df73fbd60) at vm/llvm/state.cpp:337
#46 0x00000000007c16df in rubinius::jit_llvm_trampoline (state=0x7f9df73fbd60) at vm/llvm/state.cpp:188
#47 0x000000000072f1c1 in rubinius::Thread::in_new_thread (ptr=0x24c2650) at vm/builtin/thread.cpp:283
#48 0x00007f9e0df2cf18 in start_thread (arg=0x7f9df73fc700) at pthread_create.c:308
#49 0x00007f9e0cbdcb9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by YorickPeterse** [comment]
@ghazel Can you try your app using Rbx compiled from Git? #3245 has supposedly been fixed, which looks like either a similar or the same issue.

**Comment by jc00ke** [comment]
Also seeing this (or something like it) on the Calagator specs on Travis: https://travis-ci.org/calagator/calagator/jobs/46600954

However, I'm not seeing those failures locally on ffd327fb5fedc4c911f11b21425b764b254ee34c

**Comment by brixen** [comment]
@ghazel this should be fixed. Please re-open if you continue to see it on 2.5.0+.
