### ISSUE TITLE
rubocop fails with Coercion error

### ISSUE THREAD

**Issue by tmornini** [rubinius/rubinius#3278]
Hey guys, thought you'd want to see this. Current versions of everything.

```
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.0.
Inspecting 273 files
..........................................................................................................................................Coercion error: nil.to_int => Fixnum failed
kernel/common/type.rb:36:in `coerce_to_failed'
kernel/common/type.rb:152:in `coerce_to_collection_length'
kernel/common/array.rb:57:in `initialize'
kernel/common/array.rb:1664:in `to_a'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/ast-2.0.0/lib/ast/node.rb:61:in `initialize'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/astrolabe-1.3.0/lib/astrolabe/node.rb:27:in `initialize'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/astrolabe-1.3.0/lib/astrolabe/builder.rb:25:in `n'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/parser-2.2.0.1/lib/parser/builders/default.rb:182:in `array'
ruby21.y:981:in `_reduce_291'
:in `call'
kernel/bootstrap/proc.rb:20:in `call'
kernel/common/throw_catch.rb:30:in `catch'
kernel/common/throw_catch.rb:7:in `register'
kernel/common/throw_catch.rb:29:in `catch'
cparse.c:in `_racc_do_parse_c'
/home/travis/.rvm/rubies/rbx-2.4.1/gems/gems/racc-1.4.12/lib/racc/parser.rb:271:in `do_parse'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/parser-2.2.0.1/lib/parser/base.rb:175:in `parse'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/parser-2.2.0.1/lib/parser/base.rb:193:in `parse_with_comments'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/parser-2.2.0.1/lib/parser/base.rb:214:in `tokenize'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/processed_source.rb:67:in `parse'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/processed_source.rb:27:in `initialize'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/processed_source.rb:15:in `from_file'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/runner.rb:54:in `process_file'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/runner.rb:27:in `run'
kernel/bootstrap/array.rb:76:in `each'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/runner.rb:25:in `run'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/lib/rubocop/cli.rb:24:in `run'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/bin/rubocop:13:in `__script__'
/home/travis/.rvm/rubies/rbx-2.4.1/gems/gems/rubysl-benchmark-2.0.1/lib/rubysl/benchmark/benchmark.rb:294:in `realtime'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.28.0/bin/rubocop:12:in `__script__'
kernel/common/kernel.rb:497:in `load'
/home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/bin/rubocop:23:in `__script__'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:645:in `script'
kernel/loader.rb:799:in `main'
```

**Comment by YorickPeterse** [comment]
Looking at the stack trace this is a problem with the parser Gem, not the Rubinius parser itself. Is there a way to reproduce this?

**Comment by tmornini** [comment]
It reproduces regularly for me. I can give you repo access.

**Comment by YorickPeterse** [comment]
Seeing how this appears to be a parsing issue we'd only need a snippet of the source file triggering the problem. I'm personally a bit reluctant peeking into people's private repositories.

**Comment by tmornini** [comment]
Happy to provide the snippet if you can tell me how to locate it. :-)

**Comment by YorickPeterse** [comment]
@tmornini If you run rubocop using `-f simple` it should print out the filename before analysing it, this should make it possible to see what file is triggering the problem.

**Comment by tmornini** [comment]
We're green on rbx-2.5.0!

**Comment by jc00ke** [comment]
:fireworks: :fireworks: :fireworks:

**Comment by tmornini** [comment]
Weird, spoke too soon. Green on my laptop, still failing on Travis.

Looked things over carefully, entirely unclear what the differences would be other than OS X Yosemite -vs- Ubuntu 12.04 LTS

https://gist.github.com/tmornini/a0df2bf494ab14cee990

**Comment by brixen** [comment]
@tmornini This is a JIT bug, that's why you're seeing different behavior.

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
