### ISSUE TITLE
active record has and belongs to many .includes

### ISSUE THREAD

**Issue by qen** [rubinius/rubinius#3299]
my Project Model

```
class Project < ActiveRecord::Base 
  has_and_belongs_to_many :users, join_table: 'project_users'
end
```

when i run
```
Project.includes(:users).first
```

i get this error 
```
TypeError: failed to convert User to Array: User#to_ary returned NilClass
        from kernel/common/type.rb:50:in `coerce_to_type_error'
        from kernel/common/type.rb:31:in `execute_coerce_to'
        from kernel/common/type.rb:19:in `coerce_to'
        from kernel/common/array.rb:452:in `concat'
        from kernel/common/enumerable.rb:96:in `flat_map'
        from kernel/common/enumerable.rb:317:in `inject'
        from kernel/bootstrap/array.rb:76:in `each'
        from kernel/common/enumerable.rb:312:in `inject'
        from kernel/common/enumerable.rb:93:in `flat_map'
        from /var/www/smartph/tools/releases/1/vendor/bundle/rbx/2.1/gems/activerecord-4.2.0/lib/active_record/associations/preloader/through_association.rb:49:
in `associated_records_by_owner'
        from kernel/common/enumerable.rb:94:in `flat_map'
        from kernel/common/enumerable.rb:317:in `inject'
        from kernel/common/hash.rb:342:in `each'
        from kernel/common/enumerable.rb:312:in `inject'
        from kernel/common/enumerable.rb:93:in `flat_map'
```

what's weird is that this does not happen on my dev machine...

rbx version on my dev machine
```
rubinius 2.4.1 (2.1.0 b332f133 2014-12-04 3.5.0 JI) [x86_64-darwin14.0.0]
```
rbx version on production
```
rubinius 2.4.1 (2.1.0 b332f133 2014-12-04 3.5.0 JI) [x86_64-linux-gnu]
```

**Comment by jc00ke** [comment]
Can you try with the latest version, 2.5.1?

Also, if it's still busted, can you extract a reproduction? Thanks!

**Comment by qen** [comment]
just tested in 2.5.1 ... works as expected :+1:
