### ISSUE TITLE
Can't compile with rvm

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3304]
```
rbx-2.5.1 - #compiling - please wait
Error running '/home/braulio/.rvm/wrappers/ruby-2.2.0@rubinius/rake install --trace',
showing last 15 lines of /home/braulio/.rvm/log/1422751759_rbx-2.5.1/rake.log
2: CXX vm/builtin/jit.cpp
In file included from vm/builtin/jit.cpp:8:
/home/braulio/.rvm/src/rbx-2.5.1/vm/llvm/state.hpp:10:10: fatal error: 'llvm/IR/Module.h' file not found
#include <llvm/IR/Module.h>
         ^
1 error generated.
rake aborted!
Error compiling
/home/braulio/.rvm/gems/ruby-2.2.0@rubinius/gems/daedalus-core-0.2.0/lib/daedalus.rb:68:in `command'
/home/braulio/.rvm/gems/ruby-2.2.0@rubinius/gems/daedalus-core-0.2.0/lib/daedalus.rb:234:in `cxx_compile'
/home/braulio/.rvm/gems/ruby-2.2.0@rubinius/gems/daedalus-core-0.2.0/lib/daedalus.rb:221:in `compile'
/home/braulio/.rvm/gems/ruby-2.2.0@rubinius/gems/daedalus-core-0.2.0/lib/daedalus.rb:433:in `build'
/home/braulio/.rvm/gems/ruby-2.2.0@rubinius/gems/daedalus-core-0.2.0/lib/daedalus.rb:895:in `block (2 levels) in perform_tasks'
Tasks: TOP => install => build:build => vm/vm
Error: clang++ -I/home/braulio/.rvm/src/rbx-2.5.1/vm -I/home/braulio/.rvm/src/rbx-2.5.1/vm/include -I/home/braulio/.rvm/src/rbx-2.5.1/vm/builtin -I. -Ivm/test/cxxtest -I/home/braulio/.rvm/src/rbx-2.5.1/vendor/udis86 -I/home/braulio/.rvm/src/rbx-2.5.1/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/home/braulio/.rvm/src/rbx-2.5.1/vm/include/capi -I/home/braulio/.rvm/src/rbx-2.5.1/vendor/oniguruma -I/home/braulio/.rvm/src/rbx-2.5.1/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -mno-omit-leaf-frame-pointer -fPIC  -O2 -march=i686 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DHAVE_INOTIFY -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -DSTRERROR_R_CHAR_P -I/usr/lib/llvm-3.5/include -I/usr/lib/llvm-3.5/include -D_GNU_SOURCE -g -fPIC -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o vm/builtin/artifacts/jit.cpp.o vm/builtin/jit.cpp
```

**Comment by jc00ke** [comment]
What version of llvm do you have installed?

**Comment by YorickPeterse** [comment]
Please see the contributing guide (https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING.md), we need more than just a snippet of the compilation process' output.

**Comment by brauliobo** [comment]
@jc00ke 3.5 package in Ubuntu 14.10

**Comment by brauliobo** [comment]
also, I've got the same error with 2.4.1

**Comment by burningTyger** [comment]
you might want to cross reference to rvm, @brauliobo

**Comment by brixen** [comment]
@brauliobo could you please link to a gist of your configure.log and config.rb files.

**Comment by brauliobo** [comment]
`configure.log`:
```
Checking clang: found
Checking clang++: found
Checking bison: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': found! (version 3.5.0 - api: 305)

Checking sizeof(short): 2 bytes
Checking sizeof(int): 4 bytes
Checking sizeof(void*): 4 bytes
Checking sizeof(size_t): 4 bytes
Checking sizeof(long): 4 bytes
Checking sizeof(long long): 8 bytes
Checking sizeof(float): 4 bytes
Checking sizeof(double): 8 bytes
Checking sizeof(off_t): 4 bytes
Checking sizeof(time_t): 4 bytes
Checking for libc version: libc.so.6 found!
Checking platform endianness: little endian
Checking for tr1: found
Checking for tr1/hash definition: found
Checking for x86_32: yes
Checking for function 'backtrace': found!
Checking for function 'clock_gettime': found!
Checking for function 'nl_langinfo': found!
Checking for function 'setproctitle': not found
Checking for function 'posix_fadvise': found!
Checking for function 'strnlen': found!
Checking for function 'kqueue': not found
Checking for function 'timerfd_create': found!
Checking for function 'inotify_init': found!
Checking for function 'lchown': found!
Checking for struct tm has member tm_gmtoff: found!
Checking for struct tm has member tm_zone: found!
Checking for global 'timezone': found!
Checking for global 'tzname': found!
Checking for global 'daylight': found!
Checking for header 'zlib.h': found!
Checking for header 'openssl/ssl.h': found!
Checking for header 'alloca.h': found!
Checking for header 'string.h': found!
Checking for header 'sys/time.h': found!
Checking for header 'sys/times.h': found!
Checking for header 'sys/types.h': found!
Checking for header 'unistd.h': found!
Checking for header 'stdarg.h': found!
Checking for header 'sys/pstat.h': not found
Checking for header 'valgrind/valgrind.h': not found
Checking curses library: -lcurses
Checking if function 'strerror_r' returns char*: yes

Verifying gems...

Setting up gems...
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/staging/runtime/gems/rubinius-ast-2.3.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/staging/runtime/gems/rubinius-compiler-2.3.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/staging/runtime/gems/rubinius-melbourne-2.3.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/staging/runtime/gems/rubinius-processor-2.3.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/staging/runtime/gems/rubinius-toolset-2.3.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/ffi2-generators-0.1.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-etc-2.0.3'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-fileutils-2.0.3'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-mkmf-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-shellwords-2.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-date-2.0.9'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-delegate-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-digest-2.0.3'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-fcntl-2.0.4'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-monitor-2.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-openssl-2.2.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-optparse-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-stringio-2.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-strscan-2.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-tempfile-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-thread-2.0.2'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-tmpdir-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-uri-2.0.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-yaml-2.1.0'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/rubysl-zlib-2.0.1'
Unpacked gem: '/home/braulio/.rvm/src/rbx-2.5.1/bootstrap/gems/psych-2.0.10'

Writing configuration files...
------------------------------------------------------------------

Rubinius (8fd046f3) has been configured for the following paths:

prefix:     /home/braulio/.rvm/rubies/rbx-2.5.1
bin:        /home/braulio/.rvm/rubies/rbx-2.5.1/bin
lib:        /home/braulio/.rvm/rubies/rbx-2.5.1/library
include:    /home/braulio/.rvm/rubies/rbx-2.5.1/vm/include/capi
runtime:    /home/braulio/.rvm/rubies/rbx-2.5.1/runtime
kernel:     /home/braulio/.rvm/rubies/rbx-2.5.1/kernel
site:       /home/braulio/.rvm/rubies/rbx-2.5.1/site
vendor:     /home/braulio/.rvm/rubies/rbx-2.5.1/vendor
man:        /home/braulio/.rvm/rubies/rbx-2.5.1/man
gems:       /home/braulio/.rvm/rubies/rbx-2.5.1/gems
gems cache: /home/braulio/.rvm/src/rbx-2.5.1/vendor/cache

Run 'rake' to build, test and install Rubinius.

After building, you may add

'/home/braulio/.rvm/rubies/rbx-2.5.1/bin'

to your PATH or run commands directly from that directory.

Available commands are:

  ruby, rake, gem, irb, rdoc, ri, erb, rbx

------------------------------------------------------------------
```

**Comment by brauliobo** [comment]
Can't find `config.rb` on rvm temp dir:
```
~/.r/l/1422841393_rbx-2.5.1 ❯❯❯ pwd                                                                                                                                                         
/home/braulio/.rvm/log/1422841393_rbx-2.5.1
~/.r/l/1422841393_rbx-2.5.1 ❯❯❯ ls
bundle.log  configure.log  extract.log  rake.log  remove.src.log
```

**Comment by brixen** [comment]
@brauliobo I actually want the Rubinius configure.log. Looks like RVM is overwriting that, possibly? If RVM is overwriting it, that seriously sucks because it contains a bunch of useful information that could help explain why your system LLVM isn't working.

Sorry, we can't really help you with RVM issues. Could you try building from source?

**Comment by brixen** [comment]
@brauliobo is it possible that the build directory for Rubinius is somewhere else?

**Comment by brauliobo** [comment]
@brixen managed to clone rubinius git, checkout tag v2.5.2, run configure and rake. Got the same error, maybe it is related to llvm 3.5. The configure.log is at https://gist.github.com/brauliobo/f1ccf6aeb14f8588803b

**Comment by brixen** [comment]
@brauliobo I need config.rb as well.

**Comment by brixen** [comment]
@brauliobo also, run `llvm-config --cflags --cxxflags` and check that the `-I` path listed exists. Finally, check that `llvm/IR/Module.h` exists. If not, `ls -lR <the -I path above>`.

**Comment by brauliobo** [comment]
@brixen config.rb: https://gist.github.com/brauliobo/a28410714db220c47e67
```
~/P/o/rubinius git:tags/v2.5.2 ❯❯❯ llvm-config --cflags --cxxflags
-I/usr/lib/llvm-3.5/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fPIC
-I/usr/lib/llvm-3.5/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual
```

`/usr/lib/llvm-3.5/include` don't exist!
`llvm-3.5-dev` was not installed by rvm! Shouldn't rubinius do a check for these files?

**Comment by brauliobo** [comment]
Compiled proceed, but now got another error:
```
Running 1 tasks using 3 parallel threads
1: CXX vm/llvm/jit_memory_manager.cpp
Error: g++ -I/home/braulio/Projects/others/rubinius/vm -I/home/braulio/Projects/others/rubinius/vm/include -I/home/braulio/Projects/others/rubinius/vm/builtin -I. -Ivm/test/cxxtest -I/home/braulio/Projects/others/rubinius/vendor/udis86 -I/home/braulio/Projects/others/rubinius/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/home/braulio/Projects/others/rubinius/vm/include/capi -I/home/braulio/Projects/others/rubinius/vendor/oniguruma -I/home/braulio/Projects/others/rubinius/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -fPIC  -O2 -march=i686 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DHAVE_INOTIFY -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -DSTRERROR_R_CHAR_P -I/usr/lib/llvm-3.5/include -I/usr/lib/llvm-3.5/include -D_GNU_SOURCE -g -fPIC -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o vm/llvm/artifacts/jit_memory_manager.cpp.o vm/llvm/jit_memory_manager.cpp
```

**Comment by brauliobo** [comment]
(edited last comment)

**Comment by brixen** [comment]
@brauliobo it's not feasible to check for every include file specifically. We expect the package to be installed.

I'll build a Virtual Box machine with 14.10 and get the build to complete.

**Comment by brixen** [comment]
@brauliobo from you config.rb it looks like gcc is 4.9. I've built with no issue on an ubuntu 14.10 box downloaded from http://www.vagrantbox.es/ and my gcc version is below:

```
vagrant@vagrant-ubuntu-utopic-64:~$ gcc --version
gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Is there something special about your 14.10 or is it vanilla?

**Comment by brauliobo** [comment]
@brixen It is vanilla with few exceptions on `/etc/apt/sources.list.d`. I used the same version as yours:
```
~/P/n/cirandas git:nodes-and-new-spreadsheet ❯❯❯ gcc --version                                                                          
gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by brauliobo** [comment]
@brixen the problem really seems to be with the option `-Werror`. Grepping for it I see it option on a number of files

**Comment by brauliobo** [comment]
commenting `-Werror` on `rakelib/blueprint.rb` fixed the problem.

**Comment by brauliobo** [comment]
Another error: `/usr/bin/ld: can't find library -ledit'. I think this and the llvm include files should be check on `configure`

**Comment by brixen** [comment]
@brauliobo I did not comment out `-Werror` so I'm not sure why your system is having an issue with it.

For some reason, the llvm package does not correctly include the dependency for `-ledit`. You need to install `libedit-dev`.

**Comment by YorickPeterse** [comment]
The libedit requirement is a recent requirement of LLVM, see http://rubini.us/doc/en/getting-started/requirements/ for the specific package names required. It's possible `llvm-config` is, once again, adding extra warning flags that trigger errors on Rubinius (due to `-Werror`). We've had several cases like this in the past, resulting in various flags being blacklisted (e.g. https://github.com/rubinius/rubinius/blob/a807be81062807d061ca381194888387ebe80285/rakelib/blueprint.rb#L223-L225)

**Comment by brixen** [comment]
`-Werror` is always on for the vm files, so that's not LLVM's fault here.

**Comment by brauliobo** [comment]
end result: removed `-Werror` and installed `libedit-dev` and finished compilation (although some mspec tests failed).

but still I depend on a ruby manager to install it on the userspace, so currently I can't use rubinius.

**Comment by hassan** [comment]
@brauliobo - see `rvm help mount`

**Comment by brixen** [comment]
@brauliobo could you try `rvm use rbx-2.5.2 --install --binary --fuzzy`

**Comment by brauliobo** [comment]
@hassan nice, will try that

@brixen didn't work:
```
~/P/n/cirandas git:nodes-and-new-spreadsheet ❯❯❯ rvm use rbx-2.5.2 --install --binary --fuzzy                                                                                     
rbx-2.5.2 is not installed - installing.
Searching for binary rubies, this might take some time.

Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm rbx-2.5.2 do rvm gemset create ' first, or append '--create'.
``'

**Comment by brixen** [comment]
@brauliobo could you check with the RVM folks about that?

The index for Rubinius binaries (http://binaries.rubini.us) lists this:

http://binaries.rubini.us/ubuntu/14.10/x86_64/rubinius-2.5.2.tar.bz2

And I can access that file. So, either your RVM is broken for installing binaries, or the system matching is different than expected.

**Comment by brixen** [comment]
@brauliobo hm, I think I just realized what may be the issue: Is your system 32bit?

**Comment by brauliobo** [comment]
@brixen yeah, my system is 32bit. I chose because it use less memory. But yeah, maybe the next time I format I use a 64bit system.

**Comment by brixen** [comment]
@brauliobo heh, I'm so used to people using 64bit that it totally didn't register, sorry! I'll build a 32bit unicorn vbox machine and see if 1) I can repro your issue finally, and 2) build you a binary.

**Comment by brixen** [comment]
@brauliobo the issue you're hitting on the build comes from the LLVM header files and gcc. I can't fix it.

However, I installed the clang package and built 2.5.2 with `--cc=clang --cxx=clang++` and uploaded a binary. Please retry `rvm use rbx-2.5.2 --install --binary --fuzzy` to install 2.5.2 or build with clang.

**Comment by brauliobo** [comment]
@brixen nice brixen, seems llvm can't be compiled with gcc. rvm should use these options to build rubinius.

just used your binary, it works!

**Comment by weibel** [comment]
After much trial and error i made rbx compile with
```CXXFLAGS=-Wno-undefined-bool-conversion bash -c 'rvm install rbx'```
