### ISSUE TITLE
Exception running Puma: Unable to select on IO set (descriptor too big?) (IOError)

### ISSUE THREAD

**Issue by tmornini** [rubinius/rubinius#3313]
```
v3 $ SUBLEDGER_LOG_LEVEL=error SUBLEDGER_ENV=production bundle exec puma -t 4:4 --preload > /dev/null
An exception occurred running /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/bin/puma:

Unable to select on IO set (descriptor too big?) (IOError)

Backtrace:


ERROR: the VM is exiting improperly running /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/bin/puma
intended operation: :exception
associated value: nil
destination scope: unknown
An exception occurred

    Unable to select on IO set (descriptor too big?) (IOError)

Backtrace:

                   IO.select_primitive at kernel/bootstrap/io.rb:46
                             IO.select at kernel/common/io.rb:931
          Puma::Client#eagerly_finish at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems
                                         /gems/puma-2.11.0/lib/puma/client.rb:220
              { } in Puma::Server#run at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems
                                         /gems/puma-2.11.0/lib/puma/server.rb:248
                             Proc#call at kernel/bootstrap/proc.rb:20
 { } in Puma::ThreadPool#spawn_thread at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems
                                         /gems/puma-2.11.0/lib/puma/thread_pool.rb:104
                             Proc#call at kernel/bootstrap/proc.rb:20
                        Thread#__run__ at kernel/bootstrap/thread.rb:396
Error in reactor loop escaped: Bad file descriptor - select(2) failed (Errno::EBADF)2015-02-10 09:44:08 -0800: Listen loop error


    Bad file descriptor - select(2) failed (Errno::EBADF)

Backtrace:

kernel/common/io.rb:931:in `select'
/Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems/puma-2.11.0/lib/puma/reactor.rb:28:in `run_internal'
/Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems/puma-2.11.0/lib/puma/reactor.rb:126:in `run_in_thread'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/thread.rb:396:in `__run__'
Error in select: closed stream (IOError)
kernel/common/io.rb:892:in `select'
kernel/bootstrap/array.rb:97:in `map'
kernel/common/io.rb:890:in `select'
/Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems/puma-2.11.0/lib/puma/reactor.rb:28:in `run_internal'
/Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems/puma-2.11.0/lib/puma/reactor.rb:126:in `run_in_thread'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/thread.rb:396:in `__run__'
                    IO.select at kernel/common/io.rb:931
 Puma::Server#handle_servers at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:300
     { } in Puma::Server#run at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:284
                    Proc#call at kernel/bootstrap/proc.rb:20
               Thread#__run__ at kernel/bootstrap/thread.rb:396
2015-02-10 09:44:08 -0800: Listen loop error

    closed stream (IOError)

Backtrace:

             { } in IO.select at kernel/common/io.rb:892
                    Array#map at kernel/bootstrap/array.rb:97
                    IO.select at kernel/common/io.rb:890
 Puma::Server#handle_servers at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:300
     { } in Puma::Server#run at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:284
                    Proc#call at kernel/bootstrap/proc.rb:20
               Thread#__run__ at kernel/bootstrap/thread.rb:396
2015-02-10 09:44:08 -0800: Listen loop error

    closed stream (IOError)

Backtrace:

             { } in IO.select at kernel/common/io.rb:892
                    Array#map at kernel/bootstrap/array.rb:97
                    IO.select at kernel/common/io.rb:890
 Puma::Server#handle_servers at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:300
     { } in Puma::Server#run at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:284
                    Proc#call at kernel/bootstrap/proc.rb:20
               Thread#__run__ at kernel/bootstrap/thread.rb:396
2015-02-10 09:44:08 -0800: Listen loop error

    closed stream (IOError)

Backtrace:

             { } in IO.select at kernel/common/io.rb:892
                    Array#map at kernel/bootstrap/array.rb:97
                    IO.select at kernel/common/io.rb:890
 Puma::Server#handle_servers at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:300
     { } in Puma::Server#run at /Users/tmornini/.rbenv/versions/rbx-2.5.2/gems/gems
                                /puma-2.11.0/lib/puma/server.rb:284
                    Proc#call at kernel/bootstrap/proc.rb:20
               Thread#__run__ at kernel/bootstrap/thread.rb:396
2015-02-10 09:44:08 -0800: Listen loop error

    closed stream (IOError)

Backtrace:

```

**Comment by brixen** [comment]
@tmornini is this something I can run?

**Comment by tmornini** [comment]
@brixen Sure, just gave you access to the repo.

**Comment by brixen** [comment]
@tmornini awesome! I'll check it out asap. I've got a bunch of thread-related fixes on master and a few more on the way.

**Comment by brixen** [comment]
@tmornini I've loaded the app on master HEAD and also run test:spec and test:client. I couldn't get the setup done for the other tests.

I hope to release 2.5.3 tomorrow. Please re-open or file a new issue if the app doesn't work with 2.5.3.
