### ISSUE TITLE
no such file to load -- thread

### ISSUE THREAD

**Issue by saizai** [rubinius/rubinius#3393]
```
$ which -a irb
/Users/saizai/.rvm/gems/rbx-2.5.2/bin/irb
/Users/saizai/.rvm/gems/rbx-2.5.2@global/bin/irb
/Users/saizai/.rvm/rubies/rbx-2.5.2/bin/irb
/usr/bin/irb
$ irb
An exception occurred loading Rubygems:

no such file to load -- thread (LoadError)

Backtrace:

            Rubinius::CodeLoader#load_error at kernel/common/code_loader.rb:445
  Rubinius::CodeLoader#resolve_require_path at kernel/common/code_loader.rb:429
        { } in Rubinius::CodeLoader#require at kernel/common/code_loader.rb:103
                       Rubinius.synchronize at kernel/bootstrap/rubinius.rb:127
               Rubinius::CodeLoader#require at kernel/common/code_loader.rb:102
               Rubinius::CodeLoader.require at kernel/common/code_loader.rb:241
                     Kernel(Object)#require at kernel/common/kernel.rb:755
                          Object#__script__ at /Users/saizai/.rvm/rubies/rbx-2.5.2/site/rubygems.rb:9
               Rubinius::CodeLoader.require at kernel/common/code_loader.rb:247
         Rubinius::CodeLoader.load_rubygems at kernel/delta/code_loader.rb:123
                  Rubinius::Loader#rubygems at kernel/loader.rb:579
                      Rubinius::Loader#main at kernel/loader.rb:803
```

**Comment by YorickPeterse** [comment]
Can you try without RVM?

**Comment by saizai** [comment]
Would be hard to do so, since there would be path conflicts etc., short of
uninstalling the RVM version.

**Comment by brixen** [comment]
@saizai sorry, I know it's annoying when things don't work. However, we cannot debug RVM on your system, and RVM has so frequently been the cause of errors with Rubinius, that we have to assume the problem is RVM.

I suggest 1) installing 2.5.3, and 2) if you still cannot load irb, clone and build Rubinius directly from git. If you can load irb from a source build, then it must be something that isn't playing nice with RVM. And as I said above, that's RVM's problem the vast majority of the time.

We do not recommend using RVM with Rubinius.

**Comment by saizai** [comment]
I tried upgrading to ruby-2.5.3; it still errored.

I uninstalled it entirely from rvm and reinstalled 2.5.3. That worked.

No idea what the cause was.

**Comment by nidev** [comment]
Incomplete installation will be one of the reasons.

When you have the problem again, please execute 'gem env' and check all gem paths whether one of them contains 'thread' or not. I've never used rvm though, I experienced same problem when i directly executed freshly-built irb in rubinius source folder with failure of preinstalling 2.1.0 gems.

**Comment by saizai** [comment]
As it happens, I did do so at the time:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/saizai/.rvm/gems/ruby-2.2.1
  - RUBY EXECUTABLE: /Users/saizai/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/saizai/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/saizai/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/saizai/.rvm/gems/ruby-2.2.1
     - /Users/saizai/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/saizai/.rvm/gems/ruby-2.2.1/bin
     - /Users/saizai/.rvm/gems/ruby-2.2.1@global/bin
     - /Users/saizai/.rvm/rubies/ruby-2.2.1/bin
     - /Users/saizai/.rvm/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/git/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/saizai/Dropbox/android/sdk/tools
     - /Users/saizai/Dropbox/android/sdk/platform-tools
     - /usr/local/mysql/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/git/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/saizai/Dropbox/android/sdk/tools
     - /Users/saizai/Dropbox/android/sdk/platform-tools
     - /usr/local/mysql/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/git/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/saizai/Dropbox/android/sdk/tools
     - /Users/saizai/Dropbox/android/sdk/platform-tools
     - /usr/local/mysql/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin

$ /Users/saizai/.rvm/wrappers/ruby-2.2.1@rubinius/bundle
/Users/saizai/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 24 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/saizai/.rvm/gems/ruby-2.2.1@rubinius:/Users/saizai/.rvm/gems/ruby-2.2.1@global', execute `gem env` for more information
	from /Users/saizai/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/saizai/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/saizai/.rvm/gems/ruby-2.2.1@global/bin/bundle:22:in `<main>'
	from /Users/saizai/.rvm/gems/ruby-2.2.1@rubinius/bin/ruby_executable_hooks:15:in `eval'
	from /Users/saizai/.rvm/gems/ruby-2.2.1@rubinius/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by 64kramsystem** [comment]
Got the same problem, but when building from the repository, rather than from RVM.

In my case, the problem has been solved by completely erasing the repository and rebuilding. I've tried `make clean`, but evidently, it doesn't perform a full cleanup.
