### ISSUE TITLE
Add rb_struct_s_members

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3399]
As per https://twitter.com/benlovell/status/598396609513312256 it seems Oj depends on `rb_struct_s_members()`. This function seems to (as far as I can tell) just return the same as `Struct#members`.

**Comment by jemc** [comment]
We have projects that use Oj, so I'll be interested to see this resolved.

**Comment by YorickPeterse** [comment]
@jemc @benlovell @ohler55 With 2642a30c57973987d2a7b7e85b3ce1e78100a31b in place it looks like Oj should work now on Rubinius. Running `rake test` yields on failing test but this seems to be a timing issue rather than something related to Rubinius itself:

```
Finished in 0.231332s, 1474.0745 runs/s, 2770.9142 assertions/s.

  1) Failure:
FileJuice#test_time_object_early [/home/yorickpeterse/Private/Projects/ruby/oj/test/test_file.rb:233]:
Expected: 123456000
  Actual: 123456001

341 runs, 641 assertions, 1 failures, 0 errors, 0 skips
341 tests
641 assertions, 1 failures, 0 errors

1454.36 tests/s, 2733.86 assertions/s

Finished in 0.2345 seconds
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/yorickpeterse/.rubies/rbx-git/gems/gems/rake-10.4.2/lib" "/home/yorickpeterse/.rubies/rbx-git/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/test_*.rb" -v]
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/array.rb:76:in `each'
/home/yorickpeterse/.rubies/rbx-git/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/kernel.rb:498:in `load'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:656:in `script'
kernel/loader.rb:810:in `main'
Tasks: TOP => test
(See full trace by running task with --trace)
```

I also couldn't run `rake compile` as this resulted in a coercion error. I'm not sure what's causing this but simply running `gem build oj.gemspec` followed by `gem install oj-.....` works around this.
