### ISSUE TITLE
Coercion error when execute `sh` in Rakefile

### ISSUE THREAD

**Issue by RoxasShadow** [rubinius/rubinius#3453]
What happens:
```
┌[giovanni@lifestream] [/dev/ttys000] [master ⚡] 
└[~/Desktop/zanoxrb]> bundle exec rake                              
gem build zanoxrb.gemspec
  Successfully built RubyGem
  Name: zanoxrb
  Version: 0.1
  File: zanoxrb-0.1.gem
gem install *.gem
ERROR:  While executing gem ... (TypeError)
    Coercion error: nil.to_str => String failed
rake aborted!
Command failed with status (1): [gem install *.gem...]
kernel/bootstrap/proc.rb:20:in `call'
/Users/giovanni/Desktop/zanoxrb/rakefile:11:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/array.rb:76:in `each'
/Users/giovanni/.rvm/rubies/rbx-2.5.7/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
/Users/giovanni/.rvm/rubies/rbx-2.5.7/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/kernel.rb:498:in `load'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:656:in `script'
kernel/loader.rb:842:in `main'
Tasks: TOP => default => install
(See full trace by running task with --trace)
```

What makes it happen
```
task :install do
  sh 'gem install *.gem'
end
```

How I fixed it
```
task :install do
  `gem install *.gem`
end
```

Ruby version
`rubinius 2.5.7 (2.1.0 d4fdeaad 2015-06-16 3.5.0 JI) [x86_64-darwin14.3.0]`

OS infos
`Darwin lifestream 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`

With MRI 2.1 and 2.2 that works fine though.

**Comment by brixen** [comment]
@RoxasShadow could you gist your Rakefile, please?

I tried to repro this as follows, but I can't

```
$ bundle exec rake
gem install *.gem
Successfully installed bundler-1.10.4
1 gem installed
$ ls -l
total 504
-rw-r--r--  1 bshirai  staff      46 Jun 29 10:42 Rakefile
-rw-r--r--  1 bshirai  staff  250368 Jun 29 10:42 bundler-1.10.4.gem
$ cat Rakefile
task :default do
  sh 'gem install *.gem'
end
```

**Comment by brixen** [comment]
@RoxasShadow please also gist running with `--trace`.

**Comment by RoxasShadow** [comment]
Sure @brixen, you can find the broken Rakefile [here](https://github.com/RoxasShadow/zanox-rb/blob/rbx-fail/Rakefile).

This is rbx...
```
┌[giovanni@lifestream] [/dev/ttys000] [rbx-fail ⚡] [1]
└[~/Desktop/zanoxrb]> bundle exec rake --trace
** Invoke default (first_time)
** Invoke build (first_time)
** Execute build
gem build zanoxrb.gemspec
  Successfully built RubyGem
  Name: zanoxrb
  Version: 0.3
  File: zanoxrb-0.3.gem
** Invoke install (first_time)
** Execute install
gem install *.gem
ERROR:  While executing gem ... (TypeError)
    Coercion error: nil.to_str => String failed
rake aborted!
Command failed with status (1): [gem install *.gem...]
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `create_shell_runner'
kernel/bootstrap/proc.rb:20:in `call'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/giovanni/Desktop/zanoxrb/rakefile:11:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
kernel/bootstrap/array.rb:76:in `each'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/giovanni/.rvm/rubies/rbx-2.5.7/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:201:in `invoke_prerequisites'
kernel/bootstrap/array.rb:76:in `each'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/giovanni/.rvm/rubies/rbx-2.5.7/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
kernel/bootstrap/array.rb:76:in `each'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/giovanni/.rvm/gems/rbx-2.5.7@global/gems/rake-10.4.2/bin/rake:33:in `__script__'
kernel/common/kernel.rb:498:in `load'
/Users/giovanni/.rvm/gems/rbx-2.5.7/bin/rake:23:in `__script__'
kernel/common/block_environment.rb:53:in `call_on_instance'
kernel/common/eval.rb:176:in `eval'
/Users/giovanni/.rvm/gems/rbx-2.5.7/bin/ruby_executable_hooks:15:in `__script__'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:656:in `script'
kernel/loader.rb:842:in `main'
Tasks: TOP => default => install
```

...and this is mri 2.2-head
```
┌[giovanni@lifestream] [/dev/ttys001] [rbx-fail ⚡] 
└[~/Desktop/zanoxrb]> bundle exec rake --trace
** Invoke default (first_time)
** Invoke build (first_time)
** Execute build
gem build zanoxrb.gemspec
lib/zanox/version.rb:26: warning: already initialized constant Zanox::VERSION
lib/zanox/version.rb:26: warning: previous definition of VERSION was here
  Successfully built RubyGem
  Name: zanoxrb
  Version: 0.3
  File: zanoxrb-0.3.gem
** Invoke install (first_time)
** Execute install
gem install *.gem
Successfully installed zanoxrb-0.3
Parsing documentation for zanoxrb-0.3
Installing ri documentation for zanoxrb-0.3
Done installing documentation for zanoxrb after 0 seconds
1 gem installed
** Invoke test (first_time)
** Execute test
[rspec stuff here]
```

**Comment by brixen** [comment]
@RoxasShadow what version of rubygems are you using with MRI 2.2?

**Comment by brixen** [comment]
`File.exist?` is getting called on `nil` -> https://github.com/rubygems/rubygems/blob/master/lib/rubygems/package/file_source.rb#L21
because `req.download cache_dir` returns `nil` -> https://github.com/rubygems/rubygems/blob/master/lib/rubygems/request_set.rb#L160
because -> https://github.com/rubygems/rubygems/blob/master/lib/rubygems/source/installed.rb#L32

Following that through rubygems is extremely convoluted, so at this point, it's not clear to me whether the object Rubinius has is different or whether something else is going on. Rubinius 2.5.7 is using rubygems 2.4.8.

**Comment by brixen** [comment]
Apparently, it works on MRI 2.2 with rubygems 2.4.8.

**Comment by brixen** [comment]
@RoxasShadow the `sh 'gem install ...'` vs the backtick invocation is a red herring. At some point, I started getting the error with either version.

This appears to be Bundler-related. A simple `rake` completes as expected.

**Comment by brixen** [comment]
@RoxasShadow appears to work with Bundler 1.10.5. To confirm, run the following:

```
$ # edit Rakefile to switch to sh 'gem install *.gem'
$ gem uninstall -i `rbx -e 'puts Rubinius::GEMS_PATH'` bundler
$ gem install bundler
$ bundle
$ bundle exec rake
```

**Comment by RoxasShadow** [comment]
Great, your solution worked fine, thanks :+1:
