### ISSUE TITLE
NilMethod error in Oga where it's impossible to arise

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3463]
Running the script mentioned in #3461 can in rare cases lead to the following error:

```
An exception occurred running populate_queue.rb

undefined method `empty?' on nil:NilClass. (NoMethodError)

Backtrace:

                      Kernel(NilClass)#empty? (method_missing) at kernel/delta/kernel.rb:78
                                       Oga::XML::Lexer#advance at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/lexer.rb:208
              Oga::XML::Parser(Oga::XML::SaxParser)#each_token at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/parser.rb:245
                         LL::Driver(Oga::XML::SaxParser)#parse at driver.c
                   Oga::XML::Parser(Oga::XML::SaxParser)#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/parser.rb:282
                                             Oga.sax_parse_xml at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/oga.rb:41
                             Aws::Xml::Parser::OgaEngine#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/xml/parser/engines/oga.rb:14
                                        Aws::Xml::Parser#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/xml/parser.rb:29
                                 Aws::Query::Handler#parse_xml at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:53
                               { } in Aws::Query::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:29
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                          { } in Seahorse::Client::Response#on at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:43
            { } in Seahorse::Client::Http::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:139
                                                     Proc#call at kernel/bootstrap/proc.rb:20
              { } in Seahorse::Client::Http::Response#listener at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:166
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                      Seahorse::Client::Http::Response#on_done at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:130
                   Seahorse::Client::Http::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:137
                                 Seahorse::Client::Response#on at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:42
                         Seahorse::Client::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:51
                                      Aws::Query::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:27
                         Aws::Plugins::UserAgent::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/user_agent.rb:12
             Seahorse::Client::Plugins::Endpoint::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/endpoint.rb:34
                    Aws::Plugins::ParamValidator::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_validator.rb:21
  Seahorse::Client::Plugins::RaiseResponseErrors::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/raise_response_errors.rb:14
                    Aws::Plugins::ParamConverter::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_converter.rb:21
       Seahorse::Client::Plugins::ResponseTarget::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/response_target.rb:21
                        Seahorse::Client::Request#send_request at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/request.rb:70
              { } in Aws::SQS::Client#define_operation_methods at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/base.rb:207
                                      { } in Object#__script__ at populate_queue.rb:58
                                           Kernel(Object)#loop at kernel/common/kernel.rb:511
                                      { } in Object#__script__ at populate_queue.rb:56
                                           Kernel(Object)#loop at kernel/common/kernel.rb:511
                                      { } in Object#__script__ at populate_queue.rb:51
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                                                Thread#__run__ at kernel/bootstrap/thread.rb:352
```

The code in question is at https://github.com/YorickPeterse/oga/blob/5d0e8c99af86dab9f4d1840f37625bf6b964c379/lib/oga/xml/lexer.rb#L208. Here `@elements.empty?` is apparently `nil.empty?`. Unless I'm blind this is _impossible_ because `@elements` is ever only assigned an empty Array (https://github.com/YorickPeterse/oga/blob/5d0e8c99af86dab9f4d1840f37625bf6b964c379/lib/oga/xml/lexer.rb#L132) and instances of this class are not shared between threads (the lexer is deliberately set up to promote against this by passing the input in `#initialize` rather than a separate method). The only theory I can think of is that somehow the GC sets the `@elements` variable to nil.

Log output: https://gist.github.com/YorickPeterse/b72b65c4e650d7d807bf

**Comment by YorickPeterse** [comment]
Similar problem though with a different stacktrace:

```
An exception occurred running populate_queue.rb

undefined method `pop' on nil:NilClass. (NoMethodError)

Backtrace:

                         Kernel(NilClass)#pop (method_missing) at kernel/delta/kernel.rb:78
                                Oga::XML::Lexer#on_element_end at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/lexer.rb:517
                                Oga::XML::Lexer#advance_native at ext/c/lexer.rl
                                { } in Oga::XML::Lexer#advance at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/lexer.rb:204
                                     Oga::XML::Lexer#read_data at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/lexer.rb:147
                                       Oga::XML::Lexer#advance at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/lexer.rb:203
              Oga::XML::Parser(Oga::XML::SaxParser)#each_token at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/parser.rb:245
                         LL::Driver(Oga::XML::SaxParser)#parse at driver.c
                   Oga::XML::Parser(Oga::XML::SaxParser)#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/xml/parser.rb:282
                                             Oga.sax_parse_xml at /home/yorickpeterse/.gem/rbx/2.1.0/gems/oga-1.2.1/lib/oga/oga.rb:41
                             Aws::Xml::Parser::OgaEngine#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/xml/parser/engines/oga.rb:14
                                        Aws::Xml::Parser#parse at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/xml/parser.rb:29
                                 Aws::Query::Handler#parse_xml at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:53
                               { } in Aws::Query::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:29
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                          { } in Seahorse::Client::Response#on at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:43
            { } in Seahorse::Client::Http::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:139
                                                     Proc#call at kernel/bootstrap/proc.rb:20
              { } in Seahorse::Client::Http::Response#listener at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:166
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                      Seahorse::Client::Http::Response#on_done at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:130
                   Seahorse::Client::Http::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/http/response.rb:137
                                 Seahorse::Client::Response#on at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:42
                         Seahorse::Client::Response#on_success at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:51
                                      Aws::Query::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/query/handler.rb:27
                         Aws::Plugins::UserAgent::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/user_agent.rb:12
             Seahorse::Client::Plugins::Endpoint::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/endpoint.rb:34
                    Aws::Plugins::ParamValidator::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_validator.rb:21
  Seahorse::Client::Plugins::RaiseResponseErrors::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/raise_response_errors.rb:14
                    Aws::Plugins::ParamConverter::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_converter.rb:21
       Seahorse::Client::Plugins::ResponseTarget::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/response_target.rb:21
                        Seahorse::Client::Request#send_request at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/request.rb:70
              { } in Aws::SQS::Client#define_operation_methods at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/base.rb:207
                                      { } in Object#__script__ at populate_queue.rb:58
                                           Kernel(Object)#loop at kernel/common/kernel.rb:511
                                      { } in Object#__script__ at populate_queue.rb:56
                                           Kernel(Object)#loop at kernel/common/kernel.rb:511
                                      { } in Object#__script__ at populate_queue.rb:51
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                                                Thread#__run__ at kernel/bootstrap/thread.rb:352
```

**Comment by YorickPeterse** [comment]
This is at least not caused by the JIT. Running my script with `-Xint` will still produce similar errors.

**Comment by stakach** [comment]
I'm also experiencing something similar - code runs fine on jruby and mri
Seems to occur in `Thread.new` see line: https://github.com/cotag/spider-gazelle/blob/master/spec/http1_spec.rb#L253

```
undefined method `add' on nil:NilClass.
kernel/delta/kernel.rb:78:in `add (method_missing)'
kernel/bootstrap/thread.rb:161:in `initialize'
kernel/bootstrap/thread.rb:133:in `new'
/home/travis/build/cotag/spider-gazelle/spec/http1_spec.rb:253:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
/home/travis/build/cotag/spider-gazelle/lib/spider-gazelle/gazelle/request.rb:134:in `execute!'
kernel/bootstrap/proc.rb:20:in `call'
kernel/common/throw_catch.rb:30:in `catch'
kernel/common/throw_catch.rb:8:in `register'
kernel/common/throw_catch.rb:29:in `ruby_catch (catch)'
/home/travis/build/cotag/spider-gazelle/lib/spider-gazelle/gazelle/request.rb:134:in `execute!'
/home/travis/build/cotag/spider-gazelle/lib/spider-gazelle/gazelle/http1.rb:238:in `work'
kernel/common/method.rb:71:in `call'
/home/travis/build/cotag/spider-gazelle/vendor/bundle/rbx/2.1/gems/libuv-2.0.5/lib/libuv/work.rb:76:in `on_work'
/home/travis/build/cotag/spider-gazelle/vendor/bundle/rbx/2.1/gems/libuv-2.0.5/lib/libuv/mixins/listener.rb:14:in `dispatch_callback'
/home/travis/build/cotag/spider-gazelle/vendor/bundle/rbx/2.1/gems/libuv-2.0.5/lib/libuv/mixins/listener.rb:19:in `define_callback'
kernel/bootstrap/proc.rb:20:in `call'
Function.c:in `async_cb_call'
```

**Comment by stakach** [comment]
This error is very reproducible, occurs consistently when running the specs

**Comment by jemc** [comment]
@stakach - can you try running with `RBXOPT=-Xint` to see if running without the JIT solves it in your case?  I ask because I have seen similar `nil`s appearing where they don't belong, but only when the JIT kicks in for nearby methods.

**Comment by YorickPeterse** [comment]
@jemc @stakach The issue is not JIT related in this case (e.g. I tried using `-Xint` in the past). @brixen and I believe this is due to some allocation problems that @brixen is working on in the `stw` branch.

**Comment by jemc** [comment]
@YorickPeterse - maybe in *your* case it isn't JIT-related - but maybe @stakach's case is a distinct issue from yours that is more similar to mine, and is indeed JIT-related.

**Comment by brixen** [comment]
@stakach thanks for posting this issue. I've just [sent a PR](https://github.com/cotag/spider-gazelle/pull/23) to set Rubinius to allow_failures while we take a look at the issue. I'm pretty sure it's related to the allocation / GC work I'm doing now, but I'll look into it.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
