### ISSUE TITLE
2.5.8 crashes running Rubocop

### ISSUE THREAD

**Issue by tmornini** [rubinius/rubinius#3485]
`rubinius 2.5.8 (2.1.0 bef51ae3 2015-07-14 3.4 JI) [x86_64-linux-gnu]`

Side note: JRuby 1.7.21 and 9.0.0.0 both hang on rubocop 0.33.0 installation.

```
bundle exec rubocop --display-cop-names
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Inspecting 410 files
..............The Rubinius process is aborting with signal: SIGSEGV
--- begin system info ---
node info: testing-worker-linux-docker-fa820351-3357-linux-16 #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014
--- end system info ---
--- begin rubinius info ---
process info: travis rbx 4765 2.5.8 2.1.0 2015-07-14 bef51ae3 3.4 JIT
--- end rubinius info ---
--- begin system backtrace ---
rbx() [0x69956a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0) [0x7ff08a9c2cb0]
rbx(_ZN8rubinius15MonoInlineCache11check_cacheEPNS_5StateEPNS_8CallSiteEPNS_9CallFrameERNS_9ArgumentsE+0x58) [0x6f88b8]
rbx(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x1740) [0x5f1b40]
rbx(_ZN8rubinius11MachineCode19execute_specializedINS_11NoArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x21a) [0x63588a]
rbx(_ZN8rubinius8CallSite17empty_cache_vcallEPNS_5StateEPS0_PNS_9CallFrameERNS_9ArgumentsE+0x14d) [0x6cadbd]
rbx(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x166e) [0x5f1a6e]
rbx(_ZN8rubinius11MachineCode19execute_specializedINS_14ThreeArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x242) [0x6345a2]
rbx(_ZN8rubinius8CallSite19empty_cache_privateEPNS_5StateEPS0_PNS_9CallFrameERNS_9ArgumentsE+0x146) [0x6cafc6]
rbx(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x1740) [0x5f1b40]
rbx(_ZN8rubinius11MachineCode19execute_specializedINS_11OneArgumentEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x232) [0x634f72]
rbx(_ZN8rubinius8CallSite11empty_cacheEPNS_5StateEPS0_PNS_9CallFrameERNS_9ArgumentsE+0x146) [0x6cb1d6]
rbx(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x1740) [0x5f1b40]
rbx(_ZN8rubinius16BlockEnvironment19execute_interpreterEPNS_5StateEPNS_9CallFrameEPS0_RNS_9ArgumentsERNS_15BlockInvocationE+0x268) [0x6c6f48]
rbx(_ZN8rubinius16BlockEnvironment6invokeEPNS_5StateEPNS_9CallFrameEPS0_RNS_9ArgumentsERNS_15BlockInvocationE+0x85) [0x6c7e15]
rbx(_ZN8rubinius16BlockEnvironment4callEPNS_5StateEPNS_9CallFrameERNS_9ArgumentsEi+0x3d) [0x6c803d]
rbx(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x43ab) [0x5f47ab]
rbx(_ZN8rubinius16BlockEnvironment19execute_interpreterEPNS_5StateEPNS_9CallFrameEPS0_RNS_9ArgumentsERNS_15BlockInvocationE+0x268) [0x6c6f48]
rbx(_ZN8rubinius16BlockEnvironment6invokeEPNS_5StateEPNS_9CallFrameEPS0_RNS_9ArgumentsERNS_15BlockInvocationE+0x85) [0x6c7e15]
rbx(_ZN8rubinius16BlockEnvironment4callEPNS_5StateEPNS_9CallFrameERNS_9ArgumentsEi+0x3d) [0x6c803d]
rbx(rbx_yield_stack+0xb2) [0x7be132]
[0x7ff08b34439b]
--- end system backtrace ---
--- begin Ruby backtraces ---
--- Thread 1 backtrace ---
RuboCop::Cop::Cop#cop_config in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/cop.rb:123 (+6)
RuboCop::Cop::Cop#file_name_matches_any? in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/cop.rb:223 (+3)
RuboCop::Cop::Cop#relevant_file? in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/cop.rb:197 (+11)
__block__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:56 (+19)
__block__ in kernel/common/enumerable.rb:83 (+11)
Array#each in kernel/bootstrap/array.rb:76 (+53 jit)
Enumerable#each_with_object in kernel/common/enumerable.rb:81 (+26)
RuboCop::Cop::Commissioner#investigate in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:53 (+62)
RuboCop::Cop::Team#inspect_file in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cop/team.rb:33 (+66)
RuboCop::Runner#inspect_file in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:135 (+70)
__block__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:106 (+40)
Kernel#loop in kernel/common/kernel.rb:511 (+29)
RuboCop::Runner#do_inspection_loop in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100 (+17)
RuboCop::Runner#process_file in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:78 (+117)
__block__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:53 (+20)
Array#each in kernel/bootstrap/array.rb:76 (+53 jit)
RuboCop::Runner#inspect_files in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51 (+32)
RuboCop::Runner#run in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:30 (+17)
RuboCop::CLI#run in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/lib/rubocop/cli.rb:26 (+227)
__block__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/bin/rubocop:13 (+6)
Benchmark.realtime in /home/travis/.rvm/rubies/rbx-2.5.8/gems/gems/rubysl-benchmark-2.0.1/lib/rubysl/benchmark/benchmark.rb:294 (+10)
Object#__script__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/gems/rubocop-0.33.0/bin/rubocop:12 (+89)
Kernel#load in kernel/common/kernel.rb:498 (+58)
Object#__script__ in /home/travis/build/subledger/v3/vendor/bundle/rbx/2.1/bin/rubocop:23 (+148)
Rubinius::CodeLoader#load_script in kernel/delta/code_loader.rb:66 (+52)
Rubinius::CodeLoader.load_script in kernel/delta/code_loader.rb:152 (+40)
Rubinius::Loader#script in kernel/loader.rb:656 (+214)
Rubinius::Loader#main in kernel/loader.rb:842 (+77)
--- Thread 7 backtrace ---
Timeout.watch_channel in /home/travis/.rvm/rubies/rbx-2.5.8/gems/gems/rubysl-timeout-2.0.0/lib/rubysl/timeout/timeout.rb:90 (+27)
__block__ in /home/travis/.rvm/rubies/rbx-2.5.8/gems/gems/rubysl-timeout-2.0.0/lib/rubysl/timeout/timeout.rb:125 (+3)
Proc#call in kernel/bootstrap/proc.rb:0 (+204)
Thread#__run__ in kernel/bootstrap/thread.rb:352 (+117)
--- end Ruby backtraces ---
rake aborted!
Command failed with status (): [bundle exec rubocop --display-cop-names...]
kernel/bootstrap/proc.rb:20:in `call'
/home/travis/build/subledger/v3/tasks/lint.rake:14:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
kernel/bootstrap/array.rb:76:in `each'
/home/travis/.rvm/rubies/rbx-2.5.8/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
/home/travis/.rvm/rubies/rbx-2.5.8/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/kernel.rb:498:in `load'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:656:in `script'
kernel/loader.rb:842:in `main'
```

**Comment by headius** [comment]
@tmornini I was unable to reproduce the hang you mentioned on JRuby. If it persists please file an issue and we'll work with you to fix it.

**Comment by tmornini** [comment]
@headius Just tried again, no luck. Very weird. I'll open a ticket on JRuby if I see it again.

**Comment by benlovell** [comment]
Likewise, seeing this on RBX 2.5.8 here https://travis-ci.org/roidrage/lograge/jobs/77021343

**Comment by pboling** [comment]
Seeing a SIGSEGV running Rubocop on 2.5.8.  Same repo working with older 2.2.10 in same travis build:
https://travis-ci.org/intridea/hashie/jobs/87126634

**Comment by dblock** [comment]
This is still quite annoying. We all know it's not a bug in RuboCop, but now people are saying we should take RuboCop out of the build, or we have to do unnatural things like https://github.com/ruby-grape/grape/pull/1209.

**Comment by YorickPeterse** [comment]
@dblock Any patches/information/scripts that easily reproduce the problem/etc are more than welcome, comments such as "+1" or "problem still exists" aren't going to resolve the problem.

**Comment by dblock** [comment]
I spent two hours trying to narrow this down at no avail :( It also stops happening if you run rubocop enough times.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
