### ISSUE TITLE
Build failure on Alpine Linux (in Docker)

### ISSUE THREAD

**Issue by CpuID** [rubinius/rubinius#3492]
Had to install LLVM/clang 3.5.1 (by building the older .apk packages in their aports repo) due to https://github.com/rubinius/rubinius/pull/3367 not being ready, but running on Alpine 3.2, getting the following:

```
4: CXX vm/util/file.cpp
4: CXX vm/util/logger.cpp
vm/util/logger.cpp:386:54: error: use of undeclared identifier 'LOCK_EX'
        utilities::file::LockGuard guard(logger_fd_, LOCK_EX);
                                                     ^
1 error generated.
rake aborted!
Error compiling

Tasks: TOP => install => build:build => vm/vm
(See full trace by running task with --trace)
Error: clang++ -I/usr/src/rubinius-2.5.8/vm -I/usr/src/rubinius-2.5.8/vm/include -I/usr/src/rubinius-2.5.8/vm/builtin -I. -Ivm/test/cxxtest -I/usr/src/rubinius-2.5.8/vendor/libsodium/src/libsodium/include -I/usr/src/rubinius-2.5.8/vendor/udis86 -I/usr/src/rubinius-2.5.8/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/usr/src/rubinius-2.5.8/vm/include/capi -I/usr/src/rubinius-2.5.8/vendor/oniguruma -I/usr/src/rubinius-2.5.8/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -mno-omit-leaf-frame-pointer -fPIC  -O2 -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DHAVE_INOTIFY -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -I/usr/include -I/usr/include -D_DEBUG -D_GNU_SOURCE -fPIC -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o vm/util/artifacts/logger.cpp.o vm/util/logger.cpp
The command '/bin/sh -c cd "/usr/src/rubinius-${RUBINIUS_VERSION}" && gem install bundler && bundle install && ./configure --llvm-config=/usr/bin/llvm-config --libc=musl && rake install' returned a non-zero code: 1
```

Hopefully all of the required debug info is available above (including the clang++ command), let me know if you need anything else.

**Comment by CpuID** [comment]
Dockerfile to build rubinius:

```
FROM alpine:3.2

ENV RUBINIUS_VERSION "2.5.8"

RUN apk add --update curl g++ make openssl-dev ruby ruby-dev zlib-dev

RUN mkdir -p /usr/src && cd /usr/src && curl -O "https://s3.amazonaws.com/releases.rubini.us/rubinius-${RUBINIUS_VERSION}.tar.bz2" && tar xjf "rubinius-${RUBINIUS_VERSION}.tar.bz2" && rm -f "rubinius-${RUBINIUS_VERSION}.tar.bz2"

# We need to use clang/llvm version 3.5.x until https://github.com/rubinius/rubinius/pull/3367 is merged for MCJIT support (LLVM 3.6.x)
# Built via a separate container (to avoid polluting this container image with alpine-sdk)
RUN mkdir -p /usr/src/llvm-3.5-packages
COPY ./llvm-3.5/package/main/*/*.apk /usr/src/llvm-3.5-packages/
RUN apk add --allow-untrusted /usr/src/llvm-3.5-packages/*.apk && rm -rf /usr/src/llvm-3.5-packages

RUN echo "gem: --no-document" > /etc/gemrc

RUN cd "/usr/src/rubinius-${RUBINIUS_VERSION}" && gem install bundler && bundle install && ./configure --llvm-config=/usr/bin/llvm-config --libc=musl && rake install
```

Dockerfile to build llvm 3.5 (after built, mkdir package and start with 'docker run -v "$(pwd)/package:/packages" container_hash'):

```
FROM alpine:3.2

RUN apk add --update alpine-sdk && adduser -G abuild -g "Alpine Package Builder" -s /bin/sh -D builder && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir -p /usr/src && chown builder /usr/src

USER builder

ENV PACKAGER "Someone <someone@somewhere.com>"

ENV REPODEST /packages

RUN cd /usr/src && git clone git://git.alpinelinux.org/aports alpine-aports

RUN abuild-keygen -n && echo "PACKAGER_PRIVKEY=$(find /home/builder/.abuild/*.rsa -type f)" > /home/builder/.abuild/abuild.conf

# Check out the 3.5.1 version of the package metadata.
RUN cd /usr/src/alpine-aports/main/llvm && git checkout d9a67ed0d4e40377586984b295883e767aa952cf .

WORKDIR /usr/src/alpine-aports/main/llvm

CMD ["abuild", "-r"]
```

**Comment by jemc** [comment]
For me, `LOCK_EX` is defined in `#include <sys/file.h>`, as suggested here: http://www.delorie.com/djgpp/doc/libc/libc_329.html

@CpuID - can you try adding `#include <sys/file.h>` to `vm/logger.cpp` and see if that fixes it?

**Comment by CpuID** [comment]
@jemc - sure, testing now.

**Comment by CpuID** [comment]
@jemc - thanks, a good start, got past vm/util/logger.cpp fine now. Did you want that #include in the wider distribution (I can PR if you want)? or should I just patch locally for now? or both?

Getting a different error though further down:

```
3: CXX vm/util/file.cpp
4: CXX vm/util/logger.cpp
3: CXX vm/util/murmur_hash3.cpp
3: CC vm/util/random.c
3: CC vm/util/sha1.c
4: CC vm/util/siphash.c
3: CXX vm/util/spinlock.cpp
3: CC vm/util/strftime.c
4: CC vm/util/time64.c
4: CXX vm/util/timer.cpp
3: CC vm/util/timing.c
3: CC vm/util/utf8.c
4: CC vm/util/vsnprintf.c
3: CXX vm/vm.cpp
4: CXX vm/vm_thread_state.cpp
Build time: 183.547448677 seconds
1: LD vm/vm
GEN runtime/platform.conf
rake aborted!
Rubinius::FFI::Generators::BodyGuardError: Compilation error generating constants rbx.platform.signal:
	In file included from /usr/src/rubinius-2.5.8/rbx-ffi-generators-rbx-platform-signal.c:3:
	/usr/include/sys/signal.h:1:2: error: redirecting incorrect #include <sys/signal.h> to <signal.h> [-Werror,-W#warnings]
	#warning redirecting incorrect #include <sys/signal.h> to <signal.h>
	 ^
	1 error generated.
/usr/src/rubinius-2.5.8/library/ffi/generators.rb:87:in `handle'
/usr/src/rubinius-2.5.8/library/ffi/generators.rb:68:in `perform'
/usr/src/rubinius-2.5.8/library/ffi/generators/constants.rb:131:in `calculate'
/usr/src/rubinius-2.5.8/library/ffi/generators/constants.rb:63:in `initialize'
/usr/src/rubinius-2.5.8/rakelib/platform.rake:753:in `new'
/usr/src/rubinius-2.5.8/rakelib/platform.rake:753:in `block (2 levels) in <top (required)>'
/usr/src/rubinius-2.5.8/rakelib/platform.rake:10:in `open'
/usr/src/rubinius-2.5.8/rakelib/platform.rake:10:in `block in <top (required)>'
Tasks: TOP => install => build:build => kernel:build => runtime/platform.conf
(See full trace by running task with --trace)
```

**Comment by CpuID** [comment]
@jemc I may have a solution to this one, based on the fact that version of sys/signal.h is distributed with musl on alpine - https://pkgs.alpinelinux.org/package/main/x86_64/musl-dev

```
diff -urN rubinius-2.5.8.orig/rakelib/platform.rake rubinius-2.5.8/rakelib/platform.rake
--- rubinius-2.5.8.orig/rakelib/platform.rake	2015-08-28 08:19:25.135343566 +1000
+++ rubinius-2.5.8/rakelib/platform.rake	2015-08-28 08:33:32.527356943 +1000
@@ -752,7 +752,7 @@
 
     Rubinius::FFI::Generators::Constants.new 'rbx.platform.signal' do |cg|
       cg.include 'signal.h'
-      unless BUILD_CONFIG[:windows]
+      unless BUILD_CONFIG[:windows] or RUBY_PLATFORM.match(/linux-musl$/)
         cg.include 'sys/signal.h'
       end
```

Just testing a build now, will report back.

**Comment by jemc** [comment]
> Did you want that #include in the wider distribution (I can PR if you want)?

Let's patch it on `master` after we get past all the issues.  Thanks for working on this!

**Comment by CpuID** [comment]
Re patching on master, no probs. Will make sure any tweaks are noted here so everything can be covered off.

OK the patch above for signal.h get's me past the second issue. Now, the next one:

```
RBC /usr/src/rubinius-2.5.8/bootstrap/gems/rubysl-zlib-2.0.1/lib/rubysl/zlib.rb
RBC /usr/src/rubinius-2.5.8/bootstrap/gems/rubysl-zlib-2.0.1/lib/rubysl/zlib/version.rb
RBC /usr/src/rubinius-2.5.8/bootstrap/gems/rubysl-zlib-2.0.1/lib/zlib.rb
/usr/src/rubinius-2.5.8/bin/rbx ./extconf.rbc
Fatal error loading runtime kernel:
  
Unable to resolve type 'mode_t'


0x7f13897fb990: Kernel#raise in kernel/alpha.rb:149 (+47)
0x7f13897fc320: Rubinius::FFI.find_type in kernel/platform/ffi.rb:0 (+37)
0x7f13897fcb10: Rubinius::FFI::Library#find_type in kernel/platform/library.rb:268 (+90)
0x7f13897fd2f0: __block__ in kernel/platform/library.rb:213 (+7)
0x7f13897fdc10: Array#map! in kernel/bootstrap/array.rb:117 (+62)
0x7f13897fe410: Rubinius::FFI::Library#pointer_as_function in kernel/platform/library.rb:213 (+7)
0x7f13897fec40: __block__ in kernel/platform/library.rb:119 (+28)
0x7f13897ff580: Array#each in kernel/bootstrap/array.rb:76 (+55)
0x7f13897ffd80: Rubinius::FFI::Library#attach_function in kernel/platform/library.rb:117 (+95)
0x7f13898006a0: __block__ in kernel/platform/posix.rb:21 (+155)
0x7f13898010c0: __block__ in kernel/platform/posix.rb:5 (+20)
0x7f1389801ae0: Object#script in kernel/platform/posix.rb:4 (+15)
Fatal error loading runtime kernel:
  
Unable to send 'isatty' on 'Rubinius::FFI::Platform::POSIX' (Module)


0x7f13897ff5e0: Kernel#raise in kernel/alpha.rb:149 (+47)
0x7f13897ffe80: Kernel#isatty in kernel/alpha.rb:175 (+33)
0x7f1389800830: IO#tty? in kernel/common/io.rb:2332 (+15)
0x7f1389801090: __block__ in kernel/delta/rubinius.rb:3 (+14)
0x7f1389801ae0: Object#script in kernel/delta/rubinius.rb:1 (+15)
exception detected at toplevel: undefined method `add_reader' on Rubinius (Module) (NoMethodError)
kernel/delta/kernel.rb:78
kernel/delta/module.rb:141
kernel/bootstrap/array.rb:76
kernel/delta/module.rb:141
kernel/delta/options.rb:8
kernel/delta/options.rb:7
kernel/delta/options.rb:4
kernel/delta/options.rb:1
[BUG: Uncaught C++ exception]
Please report this with the following backtrace to https://github.com/rubinius/rubinius/issues
The Rubinius process is aborting
C++ backtrace not available
rake aborted!
Command failed with status (): [/usr/src/rubinius-2.5.8/bin/rbx ./extconf....]
/usr/src/rubinius-2.5.8/rakelib/gems.rake:5:in `bootstrap_rubinius'
/usr/src/rubinius-2.5.8/rakelib/gems.rake:50:in `block (3 levels) in <top (required)>'
/usr/src/rubinius-2.5.8/rakelib/gems.rake:47:in `chdir'
/usr/src/rubinius-2.5.8/rakelib/gems.rake:47:in `block (2 levels) in <top (required)>'
Tasks: TOP => install => build:build => gems:melbourne
(See full trace by running task with --trace)
```

**Comment by CpuID** [comment]
The latest issue feels partially like this older issue: https://github.com/rubinius/rubinius/issues/318 - still reading further.

**Comment by jemc** [comment]
It looks like `mode_t` is supposed to be provided by `sys/stat.h`.

**Comment by CpuID** [comment]
Yep, seems like it:

```
/usr/src/rubinius-2.5.8 # /usr/bin/grep -Ri mode_t /usr/include/* | grep umask
/usr/include/sys/stat.h:mode_t umask(mode_t);
```

Are we missing an include listing in rakelib/platform.rake for it somewhere...? Just trying to deduce where from the stack traces.

**Comment by CpuID** [comment]
So that latest issue is actually 2 or 3? different issues by the looks of it:

- [ ] Unable to resolve type 'mode_t'
- [ ] Unable to send 'isatty' on 'Rubinius::FFI::Platform::POSIX' (Module)
- [ ] exception detected at toplevel: undefined method `add_reader' on Rubinius (Module) (NoMethodError)
  - is this just related to the isatty issue? or separate?

**Comment by CpuID** [comment]
Actually, re mode_t my grep above was incorrect. It should really be in the format of type mode_t(args);

A new grep shows it's not there at all?

```
/usr/src/rubinius-2.5.8 # /usr/bin/grep -Ri mode_t\( /usr/include/*
/usr/src/rubinius-2.5.8 # 
```

**Comment by jemc** [comment]
> It should really be in the format of type mode_t(args);
Why would it be in that format?  It's a type definition, not a function.

**Comment by CpuID** [comment]
> Why would it be in that format? It's a type definition, not a function.

yea I realised that in my comment above... sorry about that heh.

So, more grepping, compared to my glibc based Ubuntu machine:

```
$ grep -Ri mode_t * | grep typedef
asm-generic/posix_types.h:typedef unsigned int	__kernel_mode_t;
drm/drm.h:typedef struct drm_agp_mode drm_agp_mode_t;
fcntl.h:typedef __mode_t mode_t;
linux/qnxtypes.h:typedef __le16 qnx4_mode_t;
x86_64-linux-gnu/asm/posix_types_32.h:typedef unsigned short	__kernel_mode_t;
x86_64-linux-gnu/sys/types.h:typedef __mode_t mode_t;
x86_64-linux-gnu/sys/ipc.h:typedef __mode_t mode_t;
x86_64-linux-gnu/sys/stat.h:typedef __mode_t mode_t;
x86_64-linux-gnu/sys/mman.h:typedef __mode_t mode_t;
xcb/xproto.h:typedef enum xcb_notify_mode_t {
xcb/xproto.h:typedef enum xcb_set_mode_t {
xcb/xproto.h:typedef enum xcb_stack_mode_t {
xcb/xproto.h:typedef enum xcb_prop_mode_t {
xcb/xproto.h:typedef enum xcb_grab_mode_t {
xcb/xproto.h:typedef enum xcb_subwindow_mode_t {
xcb/xproto.h:typedef enum xcb_arc_mode_t {
xcb/xproto.h:typedef enum xcb_coord_mode_t {
xcb/xproto.h:typedef enum xcb_led_mode_t {
xcb/xproto.h:typedef enum xcb_auto_repeat_mode_t {
xcb/xproto.h:typedef enum xcb_host_mode_t {
```

vs Alpine:

```
/usr/src/rubinius-2.5.8 # /usr/bin/grep -Ri mode_t /usr/include/* | grep typedef
/usr/include/bits/alltypes.h:typedef unsigned mode_t;
/usr/include/clang/Basic/FileManager.h:typedef unsigned short mode_t;
```

**Comment by jemc** [comment]
I think you need to use the `musl-dev` package as a dependency of rubinius on alpine.
https://pkgs.alpinelinux.org/contents?filename=stat.h&path=%25%2Fsys&pkgname=&repo=all&arch=x86_64

**Comment by jemc** [comment]
We should probably add `sys/stat.h` as a dependency to our `configure` script here: https://github.com/rubinius/rubinius/blob/master/configure#L1315 so that it's obvious we can't proceed without it.

**Comment by CpuID** [comment]
I already had that installed, seems the typedef isn't in it though:

```
/usr/src/rubinius-2.5.8 # grep mode_t /usr/include/sys/stat.h 
#define __NEED_mode_t
int chmod(const char *, mode_t);
int fchmod(int, mode_t);
int fchmodat(int, const char *, mode_t, int);
mode_t umask(mode_t);
int mkdir(const char *, mode_t);
int mknod(const char *, mode_t, dev_t);
int mkfifo(const char *, mode_t);
int mkdirat(int, const char *, mode_t);
int mknodat(int, const char *, mode_t, dev_t);
int mkfifoat(int, const char *, mode_t);
int lchmod(const char *, mode_t);
```

It's in that other alltypes.h file listed above...

**Comment by jemc** [comment]
it looks like `sys/stat.h` has an `#include <bits/alltypes.h>` on alpine, so it gets the `mode_t` from there.

**Comment by CpuID** [comment]
Interesting... yea ok.

FYI going to start a PR with all this stuff to make it easier btw... plus Travis tests :)

**Comment by CpuID** [comment]
> I wonder if the Rubinius FFI resolver is depending on the typedef being in that actually file rather than in a sub-include - it might be just grepping for typedefs in the header file...

Pretty sure your right, reading through this logic now - https://github.com/rubinius/rubinius/blob/master/library/ffi/generators/structures.rb#L85-L105

**Comment by CpuID** [comment]
Testing this now locally:

```
--- a/rakelib/platform.rake
+++ b/rakelib/platform.rake
@@ -138,6 +138,9 @@ file 'runtime/platform.conf' => deps do |task|
         s.include "unistd.h"
         s.include "time.h"
       end
+      unless RUBY_PLATFORM.match(/linux-musl$/)
+        s.include "bits/alltypes.h"
+      end
       s.include "sys/stat.h"
       s.name 'struct stat'
       s.field :st_dev, :dev_t
```

**Comment by jemc** [comment]
It looks like the scanning of headers for typedefs actually happens here:
https://github.com/rubinius/rubinius/blob/6d598c9970b60f4012307bdfbc3757bcb1cc254d/library/ffi/generators/types.rb#L73

Can you paste the `runtime/platform.conf` from your rubinius build directory, out of curiosity?  This is where the typedefs are supposed to end up.

**Comment by CpuID** [comment]
> Can you paste the runtime/platform.conf from your rubinius build directory, out of curiosity? This is where the typedefs are supposed to end up.

https://gist.github.com/CpuID/f4f56de8e50e20c5f6ed - note this is after adding in the patch from https://github.com/rubinius/rubinius/issues/3492#issuecomment-135585676

**Comment by jemc** [comment]
Hm, what happens if you add your `"bits/alltypes.h"` patch to here instead: https://github.com/rubinius/rubinius/blob/6d598c9970b60f4012307bdfbc3757bcb1cc254d/library/ffi/generators/types.rb#L52

**Comment by CpuID** [comment]
Testing now in generators/types.rb. Can confirm adding "bits/alltypes.h" to rakelib/platform.rake didn't yield the result I wanted.

**Comment by CpuID** [comment]
Tested the below, same failure :(

```
diff --git a/library/ffi/generators/types.rb b/library/ffi/generators/types.rb
index b507676..cb7babb 100644
--- a/library/ffi/generators/types.rb
+++ b/library/ffi/generators/types.rb
@@ -55,6 +55,7 @@ module FFI
         unless @platform.windows?
           io.puts "#include <sys/socket.h>"
           io.puts "#include <sys/resource.h>"
+          io.puts "#include <bits/alltypes.h>"
         end
       end
```

**Comment by CpuID** [comment]
FYI the commit that fixed https://github.com/rubinius/rubinius/issues/318 earlier is here - https://github.com/rubinius/rubinius/commit/4cbdcc305d38d30cb236876fb50ef740e10091f0

Feedback welcome, I'm a bit stumped right now... :)

**Comment by CpuID** [comment]
Just for kicks, in all places in rakelib/platform.rake that contain sys/stat.h, I added the same bits/alltypes.h include directly underneath. Still fails the same way.

**Comment by CpuID** [comment]
@jemc would love any additional input you have on this one (things to try, etc) :)

**Comment by j-mcnally** [comment]
I am also running into this problem, was curious if any progress was made on 3.0. 

The good news is im only hitting 

```
/src/rubinius-3.0/staging/bin/rbx ./extconf.rbc
Fatal error loading runtime kernel:

Unable to resolve type 'mode_t'


0x7f34b6356980: Kernel#raise in kernel/alpha.rb:149 (+47)
0x7f34b6357310: Rubinius::FFI.find_type in kernel/platform/ffi.rb:0 (+37)
0x7f34b6357b00: Rubinius::FFI::Library#find_type in kernel/platform/library.rb:268 (+90)
0x7f34b63582e0: __block__ in kernel/platform/library.rb:213 (+7)
0x7f34b6358c00: Array#map! in kernel/bootstrap/array.rb:117 (+62)
0x7f34b6359400: Rubinius::FFI::Library#pointer_as_function in kernel/platform/library.rb:213 (+7)
0x7f34b6359c30: __block__ in kernel/platform/library.rb:119 (+28)
0x7f34b635a570: Array#each in kernel/bootstrap/array.rb:76 (+55)
0x7f34b635ad70: Rubinius::FFI::Library#attach_function in kernel/platform/library.rb:117 (+95)
0x7f34b635b690: __block__ in kernel/platform/posix.rb:21 (+155)
0x7f34b635c0b0: __block__ in kernel/platform/posix.rb:5 (+20)
0x7f34b635cad0: Object#script in kernel/platform/posix.rb:4 (+15)
Fatal error loading runtime kernel:

Unable to send 'isatty' on 'Rubinius::FFI::Platform::POSIX' (Module)


0x7f34b635a5d0: Kernel#raise in kernel/alpha.rb:149 (+47)
0x7f34b635ae70: Kernel#isatty in kernel/alpha.rb:175 (+33)
0x7f34b635b820: IO#tty? in kernel/common/io.rb:2348 (+15)
0x7f34b635c080: __block__ in kernel/delta/rubinius.rb:3 (+14)
0x7f34b635cad0: Object#script in kernel/delta/rubinius.rb:1 (+15)
exception detected at toplevel: undefined method `add_reader' on Rubinius (Module) (NoMethodError)
kernel/delta/kernel.rb:78
kernel/delta/module.rb:141
kernel/bootstrap/array.rb:76
kernel/delta/module.rb:141
kernel/delta/options.rb:8
kernel/delta/options.rb:7
kernel/delta/options.rb:4
kernel/delta/options.rb:1
[BUG: Uncaught C++ exception]
Please report this with the following backtrace to https://github.com/rubinius/rubinius/issues
The Rubinius process is aborting
C++ backtrace not available
rake aborted!
Command failed with status (): [/src/rubinius-3.0/staging/bin/rbx ./extcon...]
/src/rubinius-3.0/rakelib/gems.rake:5:in `bootstrap_rubinius'
/src/rubinius-3.0/rakelib/gems.rake:29:in `block (3 levels) in <top (required)>'
/src/rubinius-3.0/rakelib/gems.rake:26:in `chdir'
/src/rubinius-3.0/rakelib/gems.rake:26:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => spec => build => build:build => gems:melbourne
```

**Comment by YorickPeterse** [comment]
@j-mcnally I don't think anybody has done any work on Alpine Linux recently, so I doubt 3.0 changes anything.

**Comment by brixen** [comment]
Closing this, see https://github.com/rubinius/rubinius/pull/3493#issuecomment-360613709
