### ISSUE TITLE
instance_eval doesn't work with Method#to_proc.

### ISSUE THREAD

**Issue by chanks** [rubinius/rubinius#3539]
```ruby
def m1(arg)
  puts arg.inspect
end

m = method(:m1)

Object.new.instance_eval(&m)
```

On MRI 2.2.3 this prints "#<Object:0x000000024a0a18>". On Rubinius it raises:

```
NoMethodError: undefined method `repoint_scope' on nil:NilClass.
	from kernel/delta/kernel.rb:78:in `repoint_scope (method_missing)'
	from kernel/common/eval.rb:38:in `instance_eval'
```

**Comment by chanks** [comment]
Forgot to say, this is on rbx 2.5.8.
