### ISSUE TITLE
Array#new_range

### ISSUE THREAD

**Issue by medols** [rubinius/rubinius#3634]
## Problem

Array#new_range does not append nil elements.

Thank you.

## How to Reproduce

```ruby
rbx-2.5.2 :001 > [0,1,2].new_range(1,4)
 => [1, 2, nil, nil] 
```
```ruby
rbx-3.22 :001 > [0,1,2].new_range(1,4)
 => [1, 2, 16779420, Rubinius::MonoInlineCache] 
```

## Configuration Details

```shell
$ rbx -v
rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.5.1 JI) [x86_64-darwin15.0.0]
```
```shell
$ rbx -v
rubinius 3.22 (2.2.2 0deebd96 2016-03-31 3.5.1) [x86_64-darwin15.3.0]
```

**Comment by medols** [comment]
En Brian ja ho ha arreglat:

https://github.com/rubinius/rubinius/issues/3634

**Comment by brixen** [comment]
@medols sorry, I messed up the commit closing the issue. :( I'll tag 3.24.

**Comment by medols** [comment]
We use a local method with 3.23, 3.24 is fine, thank you @brixen

**Comment by brixen** [comment]
@medols no problem, thanks for reporting.

**Comment by medols** [comment]
@brixen see if sinatra tests with rbx-3.47 are useful for core/io.rb

**Comment by brixen** [comment]
@medols ok, will do. Thanks.

**Comment by chuckremes** [comment]
@medols Can you elaborate on using sinatra tests for testing core/io.rb? Does it hit things that aren't currently or properly tested by the specs?

**Comment by brixen** [comment]
Here is the Travis run https://travis-ci.org/rubinius/sinatra/jobs/145880272. Looks like most of the errors are `NameError: Missing or uninitialized constant: Tilt::ErubisTemplate`

**Comment by medols** [comment]
@brixen, @chuckremes, thank you for looking.

The mac output points towards `ERROR NoMethodError: undefined method '+' on nil:NilClass.` even for the minimal test:

```shell
$ cat myapp.rb 
require 'sinatra'
get '/' do 'Hello World' end
$ rbx myapp.rb 
[2016-07-20 09:57:24] INFO  WEBrick 1.3.1
[2016-07-20 09:57:24] INFO  ruby 2.3.1 (2016-07-15) [x86_64-darwin15.5.0]
[2016-07-20 09:57:24] WARN  TCPServer Error: Address already in use - bind(2)
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick
[2016-07-20 09:57:24] INFO  WEBrick::HTTPServer#start: pid=98625 port=4567
[2016-07-20 09:57:30] ERROR NoMethodError: undefined method '+' on nil:NilClass.
	core/zed.rb:1425:in '+ (method_missing)'
	core/io.rb:2204:in 'increment_lineno'
	core/io.rb:2029:in 'read_and_yield_count_chars'
	core/io.rb:2105:in 'read_to_separator_with_limit'
	core/io.rb:2002:in 'each'
	core/io.rb:2254:in 'each'
	core/io.rb:2523:in 'gets'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:519:in '_read_data'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/utils.rb:239:in 'timeout'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:518:in '_read_data'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:529:in 'read_line'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:416:in 'read_request_line'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:200:in 'parse'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/httpserver.rb:81:in 'run'
	/Users/g2/.rvm/rubies/rbx-3.47/gems/gems/rubysl-webrick-2.0.0/lib/webrick/server.rb:295:in 'start_thread'
	core/proc.rb:20:in 'call'
```

More details:

```shell
$ uname -a
Darwin JMT.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
$ ruby -v
rubinius 3.47 (2.3.1 43e411b2 2016-07-15 3.6.2) [x86_64-darwin15.5.0]
$ git clone https://github.com/sinatra/sinatra.git
Cloning into 'sinatra'...
remote: Counting objects: 14851, done.
remote: Total 14851 (delta 0), reused 0 (delta 0), pack-reused 14851
Receiving objects: 100% (14851/14851), 5.47 MiB | 586.00 KiB/s, done.
Resolving deltas: 100% (7679/7679), done.
Checking connectivity... done.
$ cd sinatra/
$ bundle install
(...)
$ rake
no such file to load -- asciidoctor: skipping asciidoc tests
no such file to load -- builder: skipping builder tests
no such file to load -- coffee-script: skipping coffee tests
no such file to load -- creole: skipping creole tests
no such file to load -- erubis: skipping erubis tests
no such file to load -- haml: skipping haml tests
puma is not installed, skipping integration tests
thin is not installed, skipping integration tests
reel is not installed, skipping integration tests
HTTP is not installed, skipping integration tests
RACK_ENV=development exec "/Users/g2/.rvm/rubies/rbx-3.47/bin/rbx" -w -I "/Users/g2/test/sinatra/lib" "/Users/g2/test/sinatra/test/integration/app.rb" -s webrick -o 127.0.0.1 -p 5034 -e development 2>&1
loading
starting
[2016-07-19 12:14:18] INFO  WEBrick 1.3.1
[2016-07-19 12:14:18] INFO  ruby 2.3.1 (2016-07-15) [x86_64-darwin15.5.0]
== Sinatra (v2.0.0-alpha) has taken the stage on 5034 for development with backup from WEBrick
[2016-07-19 12:14:18] INFO  WEBrick::HTTPServer#start: pid=98332 port=5034
[2016-07-19 12:14:18] ERROR NoMethodError: undefined method '+' on nil:NilClass.
	core/zed.rb:1425:in '+ (method_missing)'
	core/io.rb:2204:in 'increment_lineno'
	core/io.rb:2029:in 'read_and_yield_count_chars'
	core/io.rb:2105:in 'read_to_separator_with_limit'
	core/io.rb:2002:in 'each'
	core/io.rb:2254:in 'each'
	core/io.rb:2523:in 'gets'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:519:in '_read_data'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/utils.rb:239:in 'timeout'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:518:in '_read_data'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:529:in 'read_line'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:416:in 'read_request_line'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httprequest.rb:200:in 'parse'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/httpserver.rb:81:in 'run'
	/Users/g2/.rvm/gems/rbx-3.47@global/gems/rubysl-webrick-2.0.0/lib/webrick/server.rb:295:in 'start_thread'
	core/proc.rb:20:in 'call'
(...)
```

**Comment by medols** [comment]
Tried to build a sinatra independent spec without much success.

**Comment by chuckremes** [comment]
@medols I will look at that today. This is failing because `@lineno` is apparently `nil` for this IO instance. I don't see how that could happen since all initializers set it to 0, so I'm sure it's something tricky.

BTW, I confirmed this error on my local system. Fix coming today.

**Comment by chuckremes** [comment]
@medols Release 3.48 fixes your issue. Thanks for the report.

**Comment by medols** [comment]
@chuckremes Thank you for the fix.
