### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by kallisti5** [rubinius/rubinius#3654]
```
Building native extensions.  This could take a while...
Installed rubysl-zlib (2.0.1)
Installed rb-readline (0.5.3)
Running 1 tasks using 3 parallel threads
1: GN machine/test/runner.cpp
1: CXX machine/test/runner.cpp
In file included from machine/test/cxxtest/cxxtest/RealDescriptions.h:9:0,
                 from machine/test/cxxtest/cxxtest/TestRunner.h:11,
                 from machine/test/runner.cpp:13:
machine/test/cxxtest/cxxtest/TestSuite.h: In instantiation of ‘bool CxxTest::equals(X, Y) [with X = long unsigned int; Y = long int]’:
machine/test/cxxtest/cxxtest/TestSuite.h:56:21:   required from ‘void CxxTest::doAssertEquals(const char*, unsigned int, const char*, X, const char*, Y, const char*) [with X = long unsigned int; Y = long int]’
./machine/test/test_bignum.hpp:651:5:   required from here
machine/test/cxxtest/cxxtest/TestSuite.h:47:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         return (x == y);
                   ^
machine/test/cxxtest/cxxtest/TestSuite.h: In instantiation of ‘bool CxxTest::equals(X, Y) [with X = long long unsigned int; Y = long long int]’:
machine/test/cxxtest/cxxtest/TestSuite.h:56:21:   required from ‘void CxxTest::doAssertEquals(const char*, unsigned int, const char*, X, const char*, Y, const char*) [with X = long long unsigned int; Y = long long int]’
./machine/test/test_bignum.hpp:722:5:   required from here
machine/test/cxxtest/cxxtest/TestSuite.h:47:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
Error: g++ -I/home/kallisti5/Code/rubinius/machine -I/home/kallisti5/Code/rubinius/machine/include -I/home/kallisti5/Code/rubinius/machine/builtin -I. -Imachine/test/cxxtest -I/home/kallisti5/Code/rubinius/vendor/libsodium/src/libsodium/include -I/home/kallisti5/Code/rubinius/vendor/udis86 -I/home/kallisti5/Code/rubinius/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/home/kallisti5/Code/rubinius/machine/include/capi -I/home/kallisti5/Code/rubinius/vendor/oniguruma -I/home/kallisti5/Code/rubinius/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -fPIC  -O2 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_CLOCK_GETTIME -DHAVE_NL_LANGINFO -DHAVE_POSIX_FADVISE -DHAVE_STRNLEN -DHAVE_TIMERFD -DHAVE_INOTIFY -DHAVE_STRUCT_STAT_ST_ATIM -DHAVE_STRUCT_STAT_ST_MTIM -DHAVE_STRUCT_STAT_ST_CTIM -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -DSTRERROR_R_CHAR_P -I/home/kallisti5/Code/rubinius/vendor/rapidjson -I/usr/lib/llvm-3.8/include -I/usr/lib/llvm-3.8/include -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wall -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -g -D_GNU_SOURCE -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o machine/test/artifacts/runner.cpp.o machine/test/runner.cpp
rake aborted!
Error compiling
/var/lib/gems/2.3.0/gems/daedalus-core-0.5.0/lib/daedalus.rb:68:in `command'
/var/lib/gems/2.3.0/gems/daedalus-core-0.5.0/lib/daedalus.rb:234:in `cxx_compile'
/var/lib/gems/2.3.0/gems/daedalus-core-0.5.0/lib/daedalus.rb:221:in `compile'
/var/lib/gems/2.3.0/gems/daedalus-core-0.5.0/lib/daedalus.rb:433:in `build'
/var/lib/gems/2.3.0/gems/daedalus-core-0.5.0/lib/daedalus.rb:895:in `block (2 levels) in perform_tasks'
Tasks: TOP => default => spec => vm:test => machine/test/runner
(See full trace by running task with --trace)
```

**Comment by brixen** [comment]
@kallisti5 could you try building with clang? Since you're on 16.04, the default clang and llvm packages should be sufficient.

**Comment by brixen** [comment]
@kallisti5 if `./configure` doesn't detect `clang` and `clang++` automatically, you can pass `--cc=<whatever> --cxx=<whatever++>` to configure.

**Comment by jc00ke** [comment]
I can confirm that the build succeeds on `16.04` when `clang` and `clang++` are specified.

```
./configure --llvm-config=llvm-config-3.6 --cc=clang-3.6 --cxx=clang++-3.6
rake build
...
./bin/rbx -v
rubinius 3.43 (2.2.2 5c6a613e 2016-07-01 3.6.2) [x86_64-linux-gnu]
```
