### ISSUE TITLE
rubinius-3.42: error: 'this' pointer cannot be null in well-defined C++ code

### ISSUE THREAD

**Issue by tamird** [rubinius/rubinius#3675]
## Problem

`ruby-install rbx` fails on OS X 10.11.5 with `rubinius-3.42/machine/oop.hpp:447:16: error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]`

## How to Reproduce

On OS X 10.11.5: `ruby-install rbx`

## Configuration Details

* Output of `rbx -v`: N/A.
* Output of `uname -a`: `Darwin Tamirs-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
`
* Distribution name (in case of Linux/BSD): N/A
* Contents of `config.rb` (as a Gist link): https://gist.github.com/tamird/a7789b01bdd0ae4c1596a920215ea746
* Contents of `configure.log` (as a Gist link): https://gist.github.com/tamird/d70b1c93e544e136b16d8a03b3774928

## Stack Trace (full build output in this case)

https://gist.github.com/tamird/478072a59694c1486cc7bc4874b6feb2

**Comment by tamird** [comment]
This also reproduces with `ruby-install rbx-2` on my system. I was able to work around both issues with `CPPFLAGS=-Wno-error ruby-install rbx{,-2}`.

**Comment by brixen** [comment]
@tamird what version of clang are you using? Is it the default Xcode or installed with Homebrew or ...?

**Comment by tamird** [comment]
It's the default provided by `xcode`.

```
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by brixen** [comment]
@tamird really odd, I have exactly the same and do not get that error.

Could you clone Rubinius and change machine/oop.hpp:447 to `return __REFERENCE_P__(reinterpret_cast<intptr_t>(this));` and see if that builds?

In other words:

```
git clone https://github.com/rubinius/rubinius
cd rubinius
./configure
rake -q build
```

**Comment by brixen** [comment]
@tamird I'm almost certain this is caused by your LLVM 3.9.0svn version. Could you paste me the output of this `/path/to/llvm-config-3.9 --cflags --cxxflags`?

**Comment by tamird** [comment]
This same thing reproduced with LLVM 3.6.

```
$ /usr/local//Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/llvm-config --cflags --cxxflags
-I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fno-common
-I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-common -Wcast-qual
```

**Comment by brixen** [comment]
@tamird Did you try compiling with the patch above?

**Comment by tamird** [comment]
Indeed, that patch fixes those errors, but then I hit these guys:
```
$ CPPFLAGS=-I$(brew --prefix openssl)/include ./configure --llvm-config /usr/local//Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/llvm-config && bundle exec rake -q build
...
4: CXX machine/builtin/string.cpp
machine/builtin/string.cpp:372:15: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
      if(((n) == -1)) {
          ~~~~^~~~~
machine/builtin/string.cpp:372:15: note: remove extraneous parentheses around the comparison to silence this warning
      if(((n) == -1)) {
         ~    ^    ~
machine/builtin/string.cpp:372:15: note: use '=' to turn this equality comparison into an assignment
      if(((n) == -1)) {
              ^~
              =
machine/builtin/string.cpp:465:9: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
      n = (n);
      ~ ^  ~
2 errors generated.
Error: clang++ -I/Users/tamird/src/rubinius/machine -I/Users/tamird/src/rubinius/machine/include -I/Users/tamird/src/rubinius/machine/builtin -I. -Imachine/test/cxxtest -I/Users/tamird/src/rubinius/vendor/libsodium/src/libsodium/include -I/Users/tamird/src/rubinius/vendor/udis86 -I/Users/tamird/src/rubinius/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/Users/tamird/src/rubinius/machine/include/capi -I/Users/tamird/src/rubinius/vendor/oniguruma -I/Users/tamird/src/rubinius/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -mno-omit-leaf-frame-pointer -fPIC -D_DARWIN_USE_64_BIT_INODE  -O2 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_NL_LANGINFO -DHAVE_STRNLEN -DHAVE_KQUEUE -DHAVE_STRUCT_STAT_ST_ATIMESPEC -DHAVE_STRUCT_STAT_ST_MTIMESPEC -DHAVE_STRUCT_STAT_ST_CTIMESPEC -DHAVE_ST_BIRTHTIME -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -I/Users/tamird/src/rubinius/vendor/rapidjson -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -D_DEBUG -D_GNU_SOURCE -fno-common -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o machine/builtin/artifacts/string.cpp.o machine/builtin/string.cpp
3: CXX machine/builtin/symbol.cpp
...
2: CXX machine/thread_nexus.cpp
machine/symbol_table.cpp:44:11: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        n = (n);
        ~ ^  ~
1 error generated.
Error: clang++ -I/Users/tamird/src/rubinius/machine -I/Users/tamird/src/rubinius/machine/include -I/Users/tamird/src/rubinius/machine/builtin -I. -Imachine/test/cxxtest -I/Users/tamird/src/rubinius/vendor/libsodium/src/libsodium/include -I/Users/tamird/src/rubinius/vendor/udis86 -I/Users/tamird/src/rubinius/vendor/libffi/include -Ivendor/double-conversion/src -DHAVE_CONFIG_H -I/Users/tamird/src/rubinius/machine/include/capi -I/Users/tamird/src/rubinius/vendor/oniguruma -I/Users/tamird/src/rubinius/vendor/libtommath -pipe -Wall -fno-omit-frame-pointer -g -mno-omit-leaf-frame-pointer -fPIC -D_DARWIN_USE_64_BIT_INODE  -O2 -DHAS_EXECINFO -DHAVE_SPT_REUSEARGV -DHAVE_NL_LANGINFO -DHAVE_STRNLEN -DHAVE_KQUEUE -DHAVE_STRUCT_STAT_ST_ATIMESPEC -DHAVE_STRUCT_STAT_ST_MTIMESPEC -DHAVE_STRUCT_STAT_ST_CTIMESPEC -DHAVE_ST_BIRTHTIME -DHAVE_TM_GMTOFF -DHAVE_TM_ZONE -DHAVE_TIMEZONE -DHAVE_TZNAME -DHAVE_DAYLIGHT -DHAVE_ALLOCA_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TIMES_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_STDARG_H -I/Users/tamird/src/rubinius/vendor/rapidjson -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -D_DEBUG -D_GNU_SOURCE -fno-common -DENABLE_LLVM -Wno-unused-function -Werror -DRBX_PROFILER -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-rtti -fvisibility-inlines-hidden    -std=c++11 -c -o machine/artifacts/symbol_table.cpp.o machine/symbol_table.cpp
rake aborted!
Error compiling
/Users/tamird/.gem/ruby/2.3.1/gems/daedalus-core-0.5.0/lib/daedalus.rb:68:in `command'
/Users/tamird/.gem/ruby/2.3.1/gems/daedalus-core-0.5.0/lib/daedalus.rb:234:in `cxx_compile'
/Users/tamird/.gem/ruby/2.3.1/gems/daedalus-core-0.5.0/lib/daedalus.rb:221:in `compile'
/Users/tamird/.gem/ruby/2.3.1/gems/daedalus-core-0.5.0/lib/daedalus.rb:433:in `build'
/Users/tamird/.gem/ruby/2.3.1/gems/daedalus-core-0.5.0/lib/daedalus.rb:895:in `block (2 levels) in perform_tasks'
Tasks: TOP => build => build:build => machine/vm
(See full trace by running task with --trace)
```

**Comment by brixen** [comment]
@tamird could you gist output of your `env` command please? Those other warnings are from code we are not going to modify. I see the same warnings under clang++-3.8 but they do not cause errors.

Since you are on OSX, you can either download the Rubinius binary for OSX directly (see [here](https://github.com/rubinius/homebrew-apps/blob/master/rubinius.rb#L5)) or use Homebrew rbx (`brew update && brew tap rubinius/apps && brew install rubinius).

**Comment by tamird** [comment]
```
$ env
TERM_PROGRAM=iTerm.app
GEM_HOME=/Users/tamird/.gem/ruby/2.3.1
TERM=xterm-256color
SHELL=/usr/local/bin/bash
TMPDIR=/var/folders/lf/1_qqs3815tzgkhtrbrjs913m0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.CaLUTAzttG/Render
BARE_PATH=/Users/tamird/bin:/usr/local/opt/ccache/libexec:/Users/tamird/.gem/ruby/2.3.1/bin:/Users/tamird/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bin:/Users/tamird/.rubies/ruby-2.3.1/bin:/Users/tamird/.pyenv/shims:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tamird/src/go/bin:/Users/tamird/.cargo/bin
TERM_PROGRAM_VERSION=3.0.2
OLDPWD=/Users/tamird/src
TERM_SESSION_ID=w0t0p1:1513AB20-72FB-4531-B6F2-BCABABB2F784
USER=tamird
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nDuFik5onm/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/tamird/src/go1.6/bin:/Users/tamird/bin:/usr/local/opt/ccache/libexec:/Users/tamird/.gem/ruby/2.3.1/bin:/Users/tamird/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bin:/Users/tamird/.rubies/ruby-2.3.1/bin:/Users/tamird/.pyenv/shims:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tamird/src/go/bin:/Users/tamird/.cargo/bin
PWD=/Users/tamird/src/rubinius
EDITOR=subl -w
GOTRACEBACK=all
LANG=en_US.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
RUBY_ENGINE=ruby
XPC_SERVICE_NAME=0
PYENV_SHELL=bash
SHLVL=1
HOME=/Users/tamird
COLORFGBG=7;0
GEM_ROOT=/Users/tamird/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0
ITERM_SESSION_ID=w0t0p1:1513AB20-72FB-4531-B6F2-BCABABB2F784
PYTHONPATH=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python
LOGNAME=tamird
GEM_PATH=/Users/tamird/.gem/ruby/2.3.1:/Users/tamird/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0
GOPATH=/Users/tamird/src/go
RUBY_ROOT=/Users/tamird/.rubies/ruby-2.3.1
RUBYOPT=
RUBY_VERSION=2.3.1
_=/usr/bin/env
```

Like I said, I've worked around this by setting CPPFLAGS=-Wno-error, but I'm definitely seeing these warnings (which are upgraded to errors) under the system clang (not 3.8).

**Comment by brixen** [comment]
@tamird I see that you have ccache in your path. You may consider removing that.

Unfortunately, I cannot repro it and I have the same OS version, same default Xcode, and I've additionally tried with llvm 3.6 and 3.8. I realize it can be frustrating when something like this doesn't work, but unless I can troubleshoot the issue, I cannot fix it.

Since we build OSX binaries every release that work on your system, I would recommend using them instead of building with source. I use chruby and this is how I install Rubinius (`brew update && brew install rubinius && mkdir ~/.rubies/rbx-X.Y && cp -r $(brew --prefix rubinius)/* ~/.rubies/rbx-X.Y`). I'll work on getting binaries to install under mkrb and that will be even more simple for you.
