### ISSUE TITLE
rubinius 3.105 fails to install in  rvm due to rubygems issue

### ISSUE THREAD

**Issue by saizai** [rubinius/rubinius#3799]
```
$ ARCHFLAGS="-arch x86_64" rvm reinstall rbx-3.105 -- --with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include
Warning! PATH is not properly set up, /Users/saizai/.rvm/gems/ruby-2.5.1/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-2.5.1
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
rbx-3.105 - #removing src/rbx-3.105..
rbx-3.105 - #removing rubies/rbx-3.105..
Checking requirements for osx_brew.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
ruby-2.5.1@rubinius - #regenerating binstubs..........
rbx-3.105 - #downloading rubinius-3.105, this may take a while depending on your connection...
rbx-3.105 - #extracting rubinius-3.105 to /Users/saizai/.rvm/src/rbx-3.105.....
rbx-3.105 - #configuring......................
rbx-3.105 - #compiling................................................................................................................................................-
cp: cannot stat '/Users/saizai/.rvm/rubies/rbx-3.105/lib/bin/gem.rb': No such file or directory
rbx-3.105 - #making binaries executable..
rbx-3.105 - #downloading rubygems-2.7.7
rbx-3.105 - #extracting rubygems-2.7.7......
rbx-3.105 - #removing old rubygems........
rbx-3.105 - #installing rubygems-2.7.7.....
Error running 'env GEM_HOME=/Users/saizai/.rvm/gems/rbx-3.105@global GEM_PATH= /Users/saizai/.rvm/rubies/rbx-3.105/bin/ruby -d /Users/saizai/.rvm/src/rubygems-2.7.7/setup.rb --no-document',
please read /Users/saizai/.rvm/log/1527666963_rbx-3.105/rubygems.install.log

$ cat /Users/saizai/.rvm/log/1527666963_rbx-3.105/rubygems.install.log
[2018-05-30 09:09:47] /Users/saizai/.rvm/rubies/rbx-3.105/bin/ruby
current path: /Users/saizai/.rvm/src/rubygems-2.7.7
PATH=/Users/saizai/.rvm/bin:/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/git/bin:/usr/local/bin:/usr/local/sbin:/Users/saizai/Dropbox/android/sdk/tools:/Users/saizai/Dropbox/android/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/opt/libpq/bin:/usr/local/opt/apr-util/bin:/usr/local/opt/apr/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/inetutils/libexec/gnubin:/usr/local/opt/e2fsprogs/sbin:/usr/local/opt/e2fsprogs/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gettext/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/local/sbin:/Users/saizai/src/google-cloud-sdk/bin:/Users/saizai/.nvm/versions/node/v9.11.1/bin:/usr/local/git/bin:/usr/local/bin:/usr/local/sbin:/Users/saizai/Dropbox/android/sdk/tools:/Users/saizai/Dropbox/android/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/opt/libpq/bin:/usr/local/opt/apr-util/bin:/usr/local/opt/apr/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/inetutils/libexec/gnubin:/usr/local/opt/e2fsprogs/sbin:/usr/local/opt/e2fsprogs/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gettext/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/local/sbin:/Users/saizai/src/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS
command(7): env GEM_HOME=/Users/saizai/.rvm/gems/rbx-3.105@global GEM_PATH= /Users/saizai/.rvm/rubies/rbx-3.105/bin/ruby -d /Users/saizai/.rvm/src/rubygems-2.7.7/setup.rb --no-document
Exception: `NoMethodError' core/type.rb:154 - undefined method `to_str' on for_lockfile:Symbol.
Exception: `TypeError' core/type.rb:156 - Coercion error: :for_lockfile.to_str => String failed
Exception: `NoMethodError' core/type.rb:195 - undefined method `to_ary' on an instance of String.
Exception: `NoMethodError' core/type.rb:195 - undefined method `to_ary' on an instance of String.
Exception: `NoMethodError' core/type.rb:154 - undefined method `to_str' on to_spec:Symbol.
Exception: `TypeError' core/type.rb:156 - Coercion error: :to_spec.to_str => String failed
Exception: `LoadError' core/code_loader.rb:303 - no such file to load -- rubygems/defaults/operating_system
Bundler 1.16.2 installed
RubyGems 2.7.5 installed
Regenerating binstubs
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["--all", "--only-executables", "--silent"] >= 0
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/pristine_command.rb:101:in `execute'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:291:in `invoke'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/setup_command.rb:586:in `regenerate_binstubs'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/setup_command.rb:155:in `execute'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:171:in `process_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:141:in `run'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/gem_runner.rb:59:in `run'
	setup.rb:46:in `__script__'
	core/code_loader.rb:132:in `run_script'
	core/code_loader.rb:119:in `load'
	core/code_loader.rb:280:in `load_script'
	core/loader.rb:667:in `script'
	core/loader.rb:852:in `main'
Bundler 1.16.2 installed
RubyGems 2.7.5 installed
Regenerating binstubs
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["--all", "--only-executables", "--silent"] >= 0
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/pristine_command.rb:101:in `execute'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:291:in `invoke'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/setup_command.rb:586:in `regenerate_binstubs'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/setup_command.rb:155:in `execute'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:171:in `process_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:141:in `run'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/gem_runner.rb:59:in `run'
	setup.rb:46:in `__script__'
	core/code_loader.rb:132:in `run_script'
	core/code_loader.rb:119:in `load'
	core/code_loader.rb:280:in `load_script'
	core/loader.rb:667:in `script'
	core/loader.rb:852:in `main'

$ gem pristine --all
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["--all"] >= 0
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/commands/pristine_command.rb:101:in `execute'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:171:in `process_args'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/command_manager.rb:141:in `run'
	/Users/saizai/.rvm/rubies/rbx-3.105/codedb/source/rubygems/gem_runner.rb:59:in `run'
	/Users/saizai/.rvm/rubies/rbx-3.105/bin/gem:21:in `__script__'
	core/code_loader.rb:132:in `run_script'
	core/code_loader.rb:119:in `load'
	core/code_loader.rb:280:in `load_script'
	core/loader.rb:667:in `script'
```

**Comment by brixen** [comment]
@saizai please don't open any other issues involving building Rubinius with RVM. I cannot help you with those, and the RVM project persistently refuses to follow my requests regarding things like not updating rubygems  or bundler. Rubinius bundles the versions of those that are known to work to avoid issues for people using Rubinius. RVM refusing to follow those requests causes unnecessary issues and wasted time.

If you have a problem building Rubinius from a git clone or from a Rubinius release tarball, I'm happy to help you resolve those.
